#!/bin/bash

BASE_REGISTRY_NAME=testregistry.localhost
REGISTRY_NAME="k3d-$BASE_REGISTRY_NAME"
REGISTRY_PORT=5111
REGISTRY="$REGISTRY_NAME:$REGISTRY_PORT"

CLUSTER_NAME=testmgmtcluster
FULL_CLUSTER_NAME="k3d-$CLUSTER_NAME"
