run:
  deadline: 3m
issues:
  skip-dirs:
    - mock*
  skip-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
linters:
  enable:
    - govet
    - gofmt
    - unconvert
    - ineffassign
    - goconst
    # - gocyclo
    - misspell
    - nakedret
    - prealloc
    - gosec
  disable-all: true
  # Run with --fast=false for more extensive checks
  fast: true
issue:
  max-same-issues: 0
  max-per-linter: 0
