version: "2"
linters:
  default: none
  enable:
    - goconst
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - mock*
      - "zz_generated.*\\.go$"
      - ".*conversion.*\\.go$"
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - mock*
      - "zz_generated.*\\.go$"
      - ".*conversion.*\\.go$"
