apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manager.yaml

patchesStrategicMerge:
  - manager_pull_policy.yaml
  - manager_image_patch.yaml
  - manager_auth_proxy_patch.yaml
