//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.
Portions Copyright © Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen-v0.23.6. DO NOT EDIT.

package v1alpha4

import (
	unsafe "unsafe"

	v1beta1 "github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AvailabilityZone)(nil), (*v1beta1.AvailabilityZone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AvailabilityZone_To_v1beta1_AvailabilityZone(a.(*AvailabilityZone), b.(*v1beta1.AvailabilityZone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AvailabilityZone)(nil), (*AvailabilityZone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AvailabilityZone_To_v1alpha4_AvailabilityZone(a.(*v1beta1.AvailabilityZone), b.(*AvailabilityZone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCICluster)(nil), (*v1beta1.AzureStackHCICluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(a.(*AzureStackHCICluster), b.(*v1beta1.AzureStackHCICluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCICluster)(nil), (*AzureStackHCICluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(a.(*v1beta1.AzureStackHCICluster), b.(*AzureStackHCICluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterList)(nil), (*v1beta1.AzureStackHCIClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList(a.(*AzureStackHCIClusterList), b.(*v1beta1.AzureStackHCIClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIClusterList)(nil), (*AzureStackHCIClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList(a.(*v1beta1.AzureStackHCIClusterList), b.(*AzureStackHCIClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterSpec)(nil), (*v1beta1.AzureStackHCIClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(a.(*AzureStackHCIClusterSpec), b.(*v1beta1.AzureStackHCIClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIClusterSpec)(nil), (*AzureStackHCIClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(a.(*v1beta1.AzureStackHCIClusterSpec), b.(*AzureStackHCIClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterStatus)(nil), (*v1beta1.AzureStackHCIClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus(a.(*AzureStackHCIClusterStatus), b.(*v1beta1.AzureStackHCIClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIClusterStatus)(nil), (*AzureStackHCIClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(a.(*v1beta1.AzureStackHCIClusterStatus), b.(*AzureStackHCIClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancer)(nil), (*v1beta1.AzureStackHCILoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(a.(*AzureStackHCILoadBalancer), b.(*v1beta1.AzureStackHCILoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCILoadBalancer)(nil), (*AzureStackHCILoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer(a.(*v1beta1.AzureStackHCILoadBalancer), b.(*AzureStackHCILoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancerList)(nil), (*v1beta1.AzureStackHCILoadBalancerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList(a.(*AzureStackHCILoadBalancerList), b.(*v1beta1.AzureStackHCILoadBalancerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCILoadBalancerList)(nil), (*AzureStackHCILoadBalancerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList(a.(*v1beta1.AzureStackHCILoadBalancerList), b.(*AzureStackHCILoadBalancerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancerSpec)(nil), (*v1beta1.AzureStackHCILoadBalancerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(a.(*AzureStackHCILoadBalancerSpec), b.(*v1beta1.AzureStackHCILoadBalancerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCILoadBalancerSpec)(nil), (*AzureStackHCILoadBalancerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(a.(*v1beta1.AzureStackHCILoadBalancerSpec), b.(*AzureStackHCILoadBalancerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancerStatus)(nil), (*v1beta1.AzureStackHCILoadBalancerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(a.(*AzureStackHCILoadBalancerStatus), b.(*v1beta1.AzureStackHCILoadBalancerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCILoadBalancerStatus)(nil), (*AzureStackHCILoadBalancerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(a.(*v1beta1.AzureStackHCILoadBalancerStatus), b.(*AzureStackHCILoadBalancerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachine)(nil), (*v1beta1.AzureStackHCIMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(a.(*AzureStackHCIMachine), b.(*v1beta1.AzureStackHCIMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachine)(nil), (*AzureStackHCIMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine(a.(*v1beta1.AzureStackHCIMachine), b.(*AzureStackHCIMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineList)(nil), (*v1beta1.AzureStackHCIMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList(a.(*AzureStackHCIMachineList), b.(*v1beta1.AzureStackHCIMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachineList)(nil), (*AzureStackHCIMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList(a.(*v1beta1.AzureStackHCIMachineList), b.(*AzureStackHCIMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineProviderCondition)(nil), (*v1beta1.AzureStackHCIMachineProviderCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition(a.(*AzureStackHCIMachineProviderCondition), b.(*v1beta1.AzureStackHCIMachineProviderCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachineProviderCondition)(nil), (*AzureStackHCIMachineProviderCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition(a.(*v1beta1.AzureStackHCIMachineProviderCondition), b.(*AzureStackHCIMachineProviderCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineSpec)(nil), (*v1beta1.AzureStackHCIMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(a.(*AzureStackHCIMachineSpec), b.(*v1beta1.AzureStackHCIMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachineSpec)(nil), (*AzureStackHCIMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(a.(*v1beta1.AzureStackHCIMachineSpec), b.(*AzureStackHCIMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineStatus)(nil), (*v1beta1.AzureStackHCIMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus(a.(*AzureStackHCIMachineStatus), b.(*v1beta1.AzureStackHCIMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachineStatus)(nil), (*AzureStackHCIMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(a.(*v1beta1.AzureStackHCIMachineStatus), b.(*AzureStackHCIMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplate)(nil), (*v1beta1.AzureStackHCIMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(a.(*AzureStackHCIMachineTemplate), b.(*v1beta1.AzureStackHCIMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachineTemplate)(nil), (*AzureStackHCIMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate(a.(*v1beta1.AzureStackHCIMachineTemplate), b.(*AzureStackHCIMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateList)(nil), (*v1beta1.AzureStackHCIMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList(a.(*AzureStackHCIMachineTemplateList), b.(*v1beta1.AzureStackHCIMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachineTemplateList)(nil), (*AzureStackHCIMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList(a.(*v1beta1.AzureStackHCIMachineTemplateList), b.(*AzureStackHCIMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateResource)(nil), (*v1beta1.AzureStackHCIMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(a.(*AzureStackHCIMachineTemplateResource), b.(*v1beta1.AzureStackHCIMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachineTemplateResource)(nil), (*AzureStackHCIMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(a.(*v1beta1.AzureStackHCIMachineTemplateResource), b.(*AzureStackHCIMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateSpec)(nil), (*v1beta1.AzureStackHCIMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(a.(*AzureStackHCIMachineTemplateSpec), b.(*v1beta1.AzureStackHCIMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIMachineTemplateSpec)(nil), (*AzureStackHCIMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(a.(*v1beta1.AzureStackHCIMachineTemplateSpec), b.(*AzureStackHCIMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIResourceReference)(nil), (*v1beta1.AzureStackHCIResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference(a.(*AzureStackHCIResourceReference), b.(*v1beta1.AzureStackHCIResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIResourceReference)(nil), (*AzureStackHCIResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference(a.(*v1beta1.AzureStackHCIResourceReference), b.(*AzureStackHCIResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachine)(nil), (*v1beta1.AzureStackHCIVirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(a.(*AzureStackHCIVirtualMachine), b.(*v1beta1.AzureStackHCIVirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIVirtualMachine)(nil), (*AzureStackHCIVirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine(a.(*v1beta1.AzureStackHCIVirtualMachine), b.(*AzureStackHCIVirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachineList)(nil), (*v1beta1.AzureStackHCIVirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList(a.(*AzureStackHCIVirtualMachineList), b.(*v1beta1.AzureStackHCIVirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIVirtualMachineList)(nil), (*AzureStackHCIVirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList(a.(*v1beta1.AzureStackHCIVirtualMachineList), b.(*AzureStackHCIVirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachineSpec)(nil), (*v1beta1.AzureStackHCIVirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec(a.(*AzureStackHCIVirtualMachineSpec), b.(*v1beta1.AzureStackHCIVirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIVirtualMachineSpec)(nil), (*AzureStackHCIVirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(a.(*v1beta1.AzureStackHCIVirtualMachineSpec), b.(*AzureStackHCIVirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachineStatus)(nil), (*v1beta1.AzureStackHCIVirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(a.(*AzureStackHCIVirtualMachineStatus), b.(*v1beta1.AzureStackHCIVirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AzureStackHCIVirtualMachineStatus)(nil), (*AzureStackHCIVirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(a.(*v1beta1.AzureStackHCIVirtualMachineStatus), b.(*AzureStackHCIVirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Image)(nil), (*v1beta1.Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Image_To_v1beta1_Image(a.(*Image), b.(*v1beta1.Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Image)(nil), (*Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Image_To_v1alpha4_Image(a.(*v1beta1.Image), b.(*Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedDisk)(nil), (*v1beta1.ManagedDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ManagedDisk_To_v1beta1_ManagedDisk(a.(*ManagedDisk), b.(*v1beta1.ManagedDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ManagedDisk)(nil), (*ManagedDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ManagedDisk_To_v1alpha4_ManagedDisk(a.(*v1beta1.ManagedDisk), b.(*ManagedDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSpec)(nil), (*v1beta1.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(a.(*NetworkSpec), b.(*v1beta1.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(a.(*v1beta1.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OSDisk)(nil), (*v1beta1.OSDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OSDisk_To_v1beta1_OSDisk(a.(*OSDisk), b.(*v1beta1.OSDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OSDisk)(nil), (*OSDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OSDisk_To_v1alpha4_OSDisk(a.(*v1beta1.OSDisk), b.(*OSDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetSpec)(nil), (*v1beta1.SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SubnetSpec_To_v1beta1_SubnetSpec(a.(*SubnetSpec), b.(*v1beta1.SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SubnetSpec)(nil), (*SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SubnetSpec_To_v1alpha4_SubnetSpec(a.(*v1beta1.SubnetSpec), b.(*SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VM)(nil), (*v1beta1.VM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_VM_To_v1beta1_VM(a.(*VM), b.(*v1beta1.VM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VM)(nil), (*VM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VM_To_v1alpha4_VM(a.(*v1beta1.VM), b.(*VM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VnetSpec)(nil), (*v1beta1.VnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_VnetSpec_To_v1beta1_VnetSpec(a.(*VnetSpec), b.(*v1beta1.VnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VnetSpec)(nil), (*VnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VnetSpec_To_v1alpha4_VnetSpec(a.(*v1beta1.VnetSpec), b.(*VnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha4.APIEndpoint)(nil), (*apiv1beta1.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint(a.(*apiv1alpha4.APIEndpoint), b.(*apiv1beta1.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1beta1.APIEndpoint)(nil), (*apiv1alpha4.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint(a.(*apiv1beta1.APIEndpoint), b.(*apiv1alpha4.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha4_AvailabilityZone_To_v1beta1_AvailabilityZone(in *AvailabilityZone, out *v1beta1.AvailabilityZone, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha4_AvailabilityZone_To_v1beta1_AvailabilityZone is an autogenerated conversion function.
func Convert_v1alpha4_AvailabilityZone_To_v1beta1_AvailabilityZone(in *AvailabilityZone, out *v1beta1.AvailabilityZone, s conversion.Scope) error {
	return autoConvert_v1alpha4_AvailabilityZone_To_v1beta1_AvailabilityZone(in, out, s)
}

func autoConvert_v1beta1_AvailabilityZone_To_v1alpha4_AvailabilityZone(in *v1beta1.AvailabilityZone, out *AvailabilityZone, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1beta1_AvailabilityZone_To_v1alpha4_AvailabilityZone is an autogenerated conversion function.
func Convert_v1beta1_AvailabilityZone_To_v1alpha4_AvailabilityZone(in *v1beta1.AvailabilityZone, out *AvailabilityZone, s conversion.Scope) error {
	return autoConvert_v1beta1_AvailabilityZone_To_v1alpha4_AvailabilityZone(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(in *AzureStackHCICluster, out *v1beta1.AzureStackHCICluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(in *AzureStackHCICluster, out *v1beta1.AzureStackHCICluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(in *v1beta1.AzureStackHCICluster, out *AzureStackHCICluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(in *v1beta1.AzureStackHCICluster, out *AzureStackHCICluster, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList(in *AzureStackHCIClusterList, out *v1beta1.AzureStackHCIClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.AzureStackHCICluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList(in *AzureStackHCIClusterList, out *v1beta1.AzureStackHCIClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList(in *v1beta1.AzureStackHCIClusterList, out *AzureStackHCIClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureStackHCICluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList(in *v1beta1.AzureStackHCIClusterList, out *AzureStackHCIClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(in *AzureStackHCIClusterSpec, out *v1beta1.AzureStackHCIClusterSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(&in.NetworkSpec, &out.NetworkSpec, s); err != nil {
		return err
	}
	out.ResourceGroup = in.ResourceGroup
	out.Location = in.Location
	out.AzureStackHCILoadBalancer = (*v1beta1.AzureStackHCILoadBalancerSpec)(unsafe.Pointer(in.AzureStackHCILoadBalancer))
	if err := Convert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.Management = in.Management
	return nil
}

// Convert_v1alpha4_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(in *AzureStackHCIClusterSpec, out *v1beta1.AzureStackHCIClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(in *v1beta1.AzureStackHCIClusterSpec, out *AzureStackHCIClusterSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(&in.NetworkSpec, &out.NetworkSpec, s); err != nil {
		return err
	}
	out.ResourceGroup = in.ResourceGroup
	out.Location = in.Location
	out.AzureStackHCILoadBalancer = (*AzureStackHCILoadBalancerSpec)(unsafe.Pointer(in.AzureStackHCILoadBalancer))
	if err := Convert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.Management = in.Management
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(in *v1beta1.AzureStackHCIClusterSpec, out *AzureStackHCIClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus(in *AzureStackHCIClusterStatus, out *v1beta1.AzureStackHCIClusterStatus, s conversion.Scope) error {
	if err := Convert_v1alpha4_VM_To_v1beta1_VM(&in.Bastion, &out.Bastion, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	out.Phase = in.Phase
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha4_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus(in *AzureStackHCIClusterStatus, out *v1beta1.AzureStackHCIClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(in *v1beta1.AzureStackHCIClusterStatus, out *AzureStackHCIClusterStatus, s conversion.Scope) error {
	if err := Convert_v1beta1_VM_To_v1alpha4_VM(&in.Bastion, &out.Bastion, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	out.Phase = in.Phase
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(in *v1beta1.AzureStackHCIClusterStatus, out *AzureStackHCIClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(in *AzureStackHCILoadBalancer, out *v1beta1.AzureStackHCILoadBalancer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(in *AzureStackHCILoadBalancer, out *v1beta1.AzureStackHCILoadBalancer, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer(in *v1beta1.AzureStackHCILoadBalancer, out *AzureStackHCILoadBalancer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer(in *v1beta1.AzureStackHCILoadBalancer, out *AzureStackHCILoadBalancer, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList(in *AzureStackHCILoadBalancerList, out *v1beta1.AzureStackHCILoadBalancerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.AzureStackHCILoadBalancer)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList(in *AzureStackHCILoadBalancerList, out *v1beta1.AzureStackHCILoadBalancerList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList(in *v1beta1.AzureStackHCILoadBalancerList, out *AzureStackHCILoadBalancerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCILoadBalancer)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList(in *v1beta1.AzureStackHCILoadBalancerList, out *AzureStackHCILoadBalancerList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(in *AzureStackHCILoadBalancerSpec, out *v1beta1.AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	out.SSHPublicKey = in.SSHPublicKey
	if err := Convert_v1alpha4_Image_To_v1beta1_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.VMSize = in.VMSize
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

// Convert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(in *AzureStackHCILoadBalancerSpec, out *v1beta1.AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(in *v1beta1.AzureStackHCILoadBalancerSpec, out *AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	out.SSHPublicKey = in.SSHPublicKey
	if err := Convert_v1beta1_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.VMSize = in.VMSize
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

// Convert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(in *v1beta1.AzureStackHCILoadBalancerSpec, out *AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(in *AzureStackHCILoadBalancerStatus, out *v1beta1.AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.ReadyReplicas = in.ReadyReplicas
	out.FailedReplicas = in.FailedReplicas
	out.Address = in.Address
	out.Port = in.Port
	out.Phase = in.Phase
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ErrorReason = (*errors.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.Selector = in.Selector
	return nil
}

// Convert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(in *AzureStackHCILoadBalancerStatus, out *v1beta1.AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(in *v1beta1.AzureStackHCILoadBalancerStatus, out *AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.ReadyReplicas = in.ReadyReplicas
	out.FailedReplicas = in.FailedReplicas
	out.Address = in.Address
	out.Port = in.Port
	out.Phase = in.Phase
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ErrorReason = (*errors.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.Selector = in.Selector
	return nil
}

// Convert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(in *v1beta1.AzureStackHCILoadBalancerStatus, out *AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(in *AzureStackHCIMachine, out *v1beta1.AzureStackHCIMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(in *AzureStackHCIMachine, out *v1beta1.AzureStackHCIMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine(in *v1beta1.AzureStackHCIMachine, out *AzureStackHCIMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine(in *v1beta1.AzureStackHCIMachine, out *AzureStackHCIMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList(in *AzureStackHCIMachineList, out *v1beta1.AzureStackHCIMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.AzureStackHCIMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList(in *AzureStackHCIMachineList, out *v1beta1.AzureStackHCIMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList(in *v1beta1.AzureStackHCIMachineList, out *AzureStackHCIMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCIMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList(in *v1beta1.AzureStackHCIMachineList, out *AzureStackHCIMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition(in *AzureStackHCIMachineProviderCondition, out *v1beta1.AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	out.Type = v1beta1.AzureStackHCIMachineProviderConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition(in *AzureStackHCIMachineProviderCondition, out *v1beta1.AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition(in *v1beta1.AzureStackHCIMachineProviderCondition, out *AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	out.Type = AzureStackHCIMachineProviderConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition(in *v1beta1.AzureStackHCIMachineProviderCondition, out *AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(in *AzureStackHCIMachineSpec, out *v1beta1.AzureStackHCIMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VMSize = in.VMSize
	if err := Convert_v1alpha4_AvailabilityZone_To_v1beta1_AvailabilityZone(&in.AvailabilityZone, &out.AvailabilityZone, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_Image_To_v1beta1_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_OSDisk_To_v1beta1_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.AllocatePublicIP = in.AllocatePublicIP
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(in *AzureStackHCIMachineSpec, out *v1beta1.AzureStackHCIMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(in *v1beta1.AzureStackHCIMachineSpec, out *AzureStackHCIMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VMSize = in.VMSize
	if err := Convert_v1beta1_AvailabilityZone_To_v1alpha4_AvailabilityZone(&in.AvailabilityZone, &out.AvailabilityZone, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OSDisk_To_v1alpha4_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.AllocatePublicIP = in.AllocatePublicIP
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(in *v1beta1.AzureStackHCIMachineSpec, out *AzureStackHCIMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus(in *AzureStackHCIMachineStatus, out *v1beta1.AzureStackHCIMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*v1beta1.VMState)(unsafe.Pointer(in.VMState))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus(in *AzureStackHCIMachineStatus, out *v1beta1.AzureStackHCIMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(in *v1beta1.AzureStackHCIMachineStatus, out *AzureStackHCIMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*VMState)(unsafe.Pointer(in.VMState))
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(in *v1beta1.AzureStackHCIMachineStatus, out *AzureStackHCIMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(in *AzureStackHCIMachineTemplate, out *v1beta1.AzureStackHCIMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(in *AzureStackHCIMachineTemplate, out *v1beta1.AzureStackHCIMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate(in *v1beta1.AzureStackHCIMachineTemplate, out *AzureStackHCIMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate(in *v1beta1.AzureStackHCIMachineTemplate, out *AzureStackHCIMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList(in *AzureStackHCIMachineTemplateList, out *v1beta1.AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.AzureStackHCIMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList(in *AzureStackHCIMachineTemplateList, out *v1beta1.AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList(in *v1beta1.AzureStackHCIMachineTemplateList, out *AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCIMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList(in *v1beta1.AzureStackHCIMachineTemplateList, out *AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(in *AzureStackHCIMachineTemplateResource, out *v1beta1.AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(in *AzureStackHCIMachineTemplateResource, out *v1beta1.AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(in *v1beta1.AzureStackHCIMachineTemplateResource, out *AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(in *v1beta1.AzureStackHCIMachineTemplateResource, out *AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(in *AzureStackHCIMachineTemplateSpec, out *v1beta1.AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(in *AzureStackHCIMachineTemplateSpec, out *v1beta1.AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(in *v1beta1.AzureStackHCIMachineTemplateSpec, out *AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(in *v1beta1.AzureStackHCIMachineTemplateSpec, out *AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference(in *AzureStackHCIResourceReference, out *v1beta1.AzureStackHCIResourceReference, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	return nil
}

// Convert_v1alpha4_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference(in *AzureStackHCIResourceReference, out *v1beta1.AzureStackHCIResourceReference, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference(in *v1beta1.AzureStackHCIResourceReference, out *AzureStackHCIResourceReference, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	return nil
}

// Convert_v1beta1_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference(in *v1beta1.AzureStackHCIResourceReference, out *AzureStackHCIResourceReference, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(in *AzureStackHCIVirtualMachine, out *v1beta1.AzureStackHCIVirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(in *AzureStackHCIVirtualMachine, out *v1beta1.AzureStackHCIVirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine(in *v1beta1.AzureStackHCIVirtualMachine, out *AzureStackHCIVirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine(in *v1beta1.AzureStackHCIVirtualMachine, out *AzureStackHCIVirtualMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList(in *AzureStackHCIVirtualMachineList, out *v1beta1.AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.AzureStackHCIVirtualMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList(in *AzureStackHCIVirtualMachineList, out *v1beta1.AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList(in *v1beta1.AzureStackHCIVirtualMachineList, out *AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCIVirtualMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList(in *v1beta1.AzureStackHCIVirtualMachineList, out *AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec(in *AzureStackHCIVirtualMachineSpec, out *v1beta1.AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	out.VMSize = in.VMSize
	if err := Convert_v1alpha4_AvailabilityZone_To_v1beta1_AvailabilityZone(&in.AvailabilityZone, &out.AvailabilityZone, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_Image_To_v1beta1_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_OSDisk_To_v1beta1_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = (*string)(unsafe.Pointer(in.BootstrapData))
	out.Identity = v1beta1.VMIdentity(in.Identity)
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.ResourceGroup = in.ResourceGroup
	out.VnetName = in.VnetName
	out.ClusterName = in.ClusterName
	out.SubnetName = in.SubnetName
	out.BackendPoolNames = *(*[]string)(unsafe.Pointer(&in.BackendPoolNames))
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	return nil
}

// Convert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec(in *AzureStackHCIVirtualMachineSpec, out *v1beta1.AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(in *v1beta1.AzureStackHCIVirtualMachineSpec, out *AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	out.VMSize = in.VMSize
	if err := Convert_v1beta1_AvailabilityZone_To_v1alpha4_AvailabilityZone(&in.AvailabilityZone, &out.AvailabilityZone, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OSDisk_To_v1alpha4_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = (*string)(unsafe.Pointer(in.BootstrapData))
	out.Identity = VMIdentity(in.Identity)
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.ResourceGroup = in.ResourceGroup
	out.VnetName = in.VnetName
	out.ClusterName = in.ClusterName
	out.SubnetName = in.SubnetName
	out.BackendPoolNames = *(*[]string)(unsafe.Pointer(&in.BackendPoolNames))
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	return nil
}

// Convert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(in *v1beta1.AzureStackHCIVirtualMachineSpec, out *AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(in *AzureStackHCIVirtualMachineStatus, out *v1beta1.AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*v1beta1.VMState)(unsafe.Pointer(in.VMState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(in *AzureStackHCIVirtualMachineStatus, out *v1beta1.AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(in *v1beta1.AzureStackHCIVirtualMachineStatus, out *AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*VMState)(unsafe.Pointer(in.VMState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(in *v1beta1.AzureStackHCIVirtualMachineStatus, out *AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_Image_To_v1beta1_Image(in *Image, out *v1beta1.Image, s conversion.Scope) error {
	out.Publisher = (*string)(unsafe.Pointer(in.Publisher))
	out.Offer = (*string)(unsafe.Pointer(in.Offer))
	out.SKU = (*string)(unsafe.Pointer(in.SKU))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.SubscriptionID = (*string)(unsafe.Pointer(in.SubscriptionID))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.Gallery = (*string)(unsafe.Pointer(in.Gallery))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.OSType = v1beta1.OSType(in.OSType)
	return nil
}

// Convert_v1alpha4_Image_To_v1beta1_Image is an autogenerated conversion function.
func Convert_v1alpha4_Image_To_v1beta1_Image(in *Image, out *v1beta1.Image, s conversion.Scope) error {
	return autoConvert_v1alpha4_Image_To_v1beta1_Image(in, out, s)
}

func autoConvert_v1beta1_Image_To_v1alpha4_Image(in *v1beta1.Image, out *Image, s conversion.Scope) error {
	out.Publisher = (*string)(unsafe.Pointer(in.Publisher))
	out.Offer = (*string)(unsafe.Pointer(in.Offer))
	out.SKU = (*string)(unsafe.Pointer(in.SKU))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.SubscriptionID = (*string)(unsafe.Pointer(in.SubscriptionID))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.Gallery = (*string)(unsafe.Pointer(in.Gallery))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.OSType = OSType(in.OSType)
	return nil
}

// Convert_v1beta1_Image_To_v1alpha4_Image is an autogenerated conversion function.
func Convert_v1beta1_Image_To_v1alpha4_Image(in *v1beta1.Image, out *Image, s conversion.Scope) error {
	return autoConvert_v1beta1_Image_To_v1alpha4_Image(in, out, s)
}

func autoConvert_v1alpha4_ManagedDisk_To_v1beta1_ManagedDisk(in *ManagedDisk, out *v1beta1.ManagedDisk, s conversion.Scope) error {
	out.StorageAccountType = in.StorageAccountType
	return nil
}

// Convert_v1alpha4_ManagedDisk_To_v1beta1_ManagedDisk is an autogenerated conversion function.
func Convert_v1alpha4_ManagedDisk_To_v1beta1_ManagedDisk(in *ManagedDisk, out *v1beta1.ManagedDisk, s conversion.Scope) error {
	return autoConvert_v1alpha4_ManagedDisk_To_v1beta1_ManagedDisk(in, out, s)
}

func autoConvert_v1beta1_ManagedDisk_To_v1alpha4_ManagedDisk(in *v1beta1.ManagedDisk, out *ManagedDisk, s conversion.Scope) error {
	out.StorageAccountType = in.StorageAccountType
	return nil
}

// Convert_v1beta1_ManagedDisk_To_v1alpha4_ManagedDisk is an autogenerated conversion function.
func Convert_v1beta1_ManagedDisk_To_v1alpha4_ManagedDisk(in *v1beta1.ManagedDisk, out *ManagedDisk, s conversion.Scope) error {
	return autoConvert_v1beta1_ManagedDisk_To_v1alpha4_ManagedDisk(in, out, s)
}

func autoConvert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(in *NetworkSpec, out *v1beta1.NetworkSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_VnetSpec_To_v1beta1_VnetSpec(&in.Vnet, &out.Vnet, s); err != nil {
		return err
	}
	out.Subnets = *(*v1beta1.Subnets)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(in *NetworkSpec, out *v1beta1.NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(in, out, s)
}

func autoConvert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(in *v1beta1.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_VnetSpec_To_v1alpha4_VnetSpec(&in.Vnet, &out.Vnet, s); err != nil {
		return err
	}
	out.Subnets = *(*Subnets)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec is an autogenerated conversion function.
func Convert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(in *v1beta1.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha4_OSDisk_To_v1beta1_OSDisk(in *OSDisk, out *v1beta1.OSDisk, s conversion.Scope) error {
	out.Name = in.Name
	out.Source = in.Source
	out.OSType = v1beta1.OSType(in.OSType)
	out.DiskSizeGB = in.DiskSizeGB
	if err := Convert_v1alpha4_ManagedDisk_To_v1beta1_ManagedDisk(&in.ManagedDisk, &out.ManagedDisk, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OSDisk_To_v1beta1_OSDisk is an autogenerated conversion function.
func Convert_v1alpha4_OSDisk_To_v1beta1_OSDisk(in *OSDisk, out *v1beta1.OSDisk, s conversion.Scope) error {
	return autoConvert_v1alpha4_OSDisk_To_v1beta1_OSDisk(in, out, s)
}

func autoConvert_v1beta1_OSDisk_To_v1alpha4_OSDisk(in *v1beta1.OSDisk, out *OSDisk, s conversion.Scope) error {
	out.Name = in.Name
	out.Source = in.Source
	out.OSType = OSType(in.OSType)
	out.DiskSizeGB = in.DiskSizeGB
	if err := Convert_v1beta1_ManagedDisk_To_v1alpha4_ManagedDisk(&in.ManagedDisk, &out.ManagedDisk, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OSDisk_To_v1alpha4_OSDisk is an autogenerated conversion function.
func Convert_v1beta1_OSDisk_To_v1alpha4_OSDisk(in *v1beta1.OSDisk, out *OSDisk, s conversion.Scope) error {
	return autoConvert_v1beta1_OSDisk_To_v1alpha4_OSDisk(in, out, s)
}

func autoConvert_v1alpha4_SubnetSpec_To_v1beta1_SubnetSpec(in *SubnetSpec, out *v1beta1.SubnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.VnetID = in.VnetID
	out.CidrBlock = in.CidrBlock
	return nil
}

// Convert_v1alpha4_SubnetSpec_To_v1beta1_SubnetSpec is an autogenerated conversion function.
func Convert_v1alpha4_SubnetSpec_To_v1beta1_SubnetSpec(in *SubnetSpec, out *v1beta1.SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_SubnetSpec_To_v1beta1_SubnetSpec(in, out, s)
}

func autoConvert_v1beta1_SubnetSpec_To_v1alpha4_SubnetSpec(in *v1beta1.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.VnetID = in.VnetID
	out.CidrBlock = in.CidrBlock
	return nil
}

// Convert_v1beta1_SubnetSpec_To_v1alpha4_SubnetSpec is an autogenerated conversion function.
func Convert_v1beta1_SubnetSpec_To_v1alpha4_SubnetSpec(in *v1beta1.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SubnetSpec_To_v1alpha4_SubnetSpec(in, out, s)
}

func autoConvert_v1alpha4_VM_To_v1beta1_VM(in *VM, out *v1beta1.VM, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.AvailabilityZone = in.AvailabilityZone
	out.VMSize = in.VMSize
	if err := Convert_v1alpha4_Image_To_v1beta1_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_OSDisk_To_v1beta1_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = in.BootstrapData
	out.State = v1beta1.VMState(in.State)
	out.Identity = v1beta1.VMIdentity(in.Identity)
	return nil
}

// Convert_v1alpha4_VM_To_v1beta1_VM is an autogenerated conversion function.
func Convert_v1alpha4_VM_To_v1beta1_VM(in *VM, out *v1beta1.VM, s conversion.Scope) error {
	return autoConvert_v1alpha4_VM_To_v1beta1_VM(in, out, s)
}

func autoConvert_v1beta1_VM_To_v1alpha4_VM(in *v1beta1.VM, out *VM, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.AvailabilityZone = in.AvailabilityZone
	out.VMSize = in.VMSize
	if err := Convert_v1beta1_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OSDisk_To_v1alpha4_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = in.BootstrapData
	out.State = VMState(in.State)
	out.Identity = VMIdentity(in.Identity)
	return nil
}

// Convert_v1beta1_VM_To_v1alpha4_VM is an autogenerated conversion function.
func Convert_v1beta1_VM_To_v1alpha4_VM(in *v1beta1.VM, out *VM, s conversion.Scope) error {
	return autoConvert_v1beta1_VM_To_v1alpha4_VM(in, out, s)
}

func autoConvert_v1alpha4_VnetSpec_To_v1beta1_VnetSpec(in *VnetSpec, out *v1beta1.VnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.CidrBlock = in.CidrBlock
	out.Group = in.Group
	return nil
}

// Convert_v1alpha4_VnetSpec_To_v1beta1_VnetSpec is an autogenerated conversion function.
func Convert_v1alpha4_VnetSpec_To_v1beta1_VnetSpec(in *VnetSpec, out *v1beta1.VnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_VnetSpec_To_v1beta1_VnetSpec(in, out, s)
}

func autoConvert_v1beta1_VnetSpec_To_v1alpha4_VnetSpec(in *v1beta1.VnetSpec, out *VnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.CidrBlock = in.CidrBlock
	out.Group = in.Group
	return nil
}

// Convert_v1beta1_VnetSpec_To_v1alpha4_VnetSpec is an autogenerated conversion function.
func Convert_v1beta1_VnetSpec_To_v1alpha4_VnetSpec(in *v1beta1.VnetSpec, out *VnetSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VnetSpec_To_v1alpha4_VnetSpec(in, out, s)
}
