//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.
Portions Copyright © Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen-v0.34. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1beta2 "github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCICluster)(nil), (*AzureStackHCICluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(a.(*v1beta2.AzureStackHCICluster), b.(*AzureStackHCICluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCICluster)(nil), (*v1beta2.AzureStackHCICluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCICluster_To_v1beta2_AzureStackHCICluster(a.(*AzureStackHCICluster), b.(*v1beta2.AzureStackHCICluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIClusterList)(nil), (*AzureStackHCIClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList(a.(*v1beta2.AzureStackHCIClusterList), b.(*AzureStackHCIClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterList)(nil), (*v1beta2.AzureStackHCIClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterList_To_v1beta2_AzureStackHCIClusterList(a.(*AzureStackHCIClusterList), b.(*v1beta2.AzureStackHCIClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIClusterSpec)(nil), (*AzureStackHCIClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(a.(*v1beta2.AzureStackHCIClusterSpec), b.(*AzureStackHCIClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterSpec)(nil), (*v1beta2.AzureStackHCIClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterSpec_To_v1beta2_AzureStackHCIClusterSpec(a.(*AzureStackHCIClusterSpec), b.(*v1beta2.AzureStackHCIClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIClusterTemplate)(nil), (*AzureStackHCIClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIClusterTemplate_To_v1beta1_AzureStackHCIClusterTemplate(a.(*v1beta2.AzureStackHCIClusterTemplate), b.(*AzureStackHCIClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterTemplate)(nil), (*v1beta2.AzureStackHCIClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterTemplate_To_v1beta2_AzureStackHCIClusterTemplate(a.(*AzureStackHCIClusterTemplate), b.(*v1beta2.AzureStackHCIClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIClusterTemplateList)(nil), (*AzureStackHCIClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIClusterTemplateList_To_v1beta1_AzureStackHCIClusterTemplateList(a.(*v1beta2.AzureStackHCIClusterTemplateList), b.(*AzureStackHCIClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterTemplateList)(nil), (*v1beta2.AzureStackHCIClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterTemplateList_To_v1beta2_AzureStackHCIClusterTemplateList(a.(*AzureStackHCIClusterTemplateList), b.(*v1beta2.AzureStackHCIClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIClusterTemplateResource)(nil), (*AzureStackHCIClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIClusterTemplateResource_To_v1beta1_AzureStackHCIClusterTemplateResource(a.(*v1beta2.AzureStackHCIClusterTemplateResource), b.(*AzureStackHCIClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterTemplateResource)(nil), (*v1beta2.AzureStackHCIClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterTemplateResource_To_v1beta2_AzureStackHCIClusterTemplateResource(a.(*AzureStackHCIClusterTemplateResource), b.(*v1beta2.AzureStackHCIClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIClusterTemplateSpec)(nil), (*AzureStackHCIClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIClusterTemplateSpec_To_v1beta1_AzureStackHCIClusterTemplateSpec(a.(*v1beta2.AzureStackHCIClusterTemplateSpec), b.(*AzureStackHCIClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterTemplateSpec)(nil), (*v1beta2.AzureStackHCIClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterTemplateSpec_To_v1beta2_AzureStackHCIClusterTemplateSpec(a.(*AzureStackHCIClusterTemplateSpec), b.(*v1beta2.AzureStackHCIClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCILoadBalancer)(nil), (*AzureStackHCILoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(a.(*v1beta2.AzureStackHCILoadBalancer), b.(*AzureStackHCILoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancer)(nil), (*v1beta2.AzureStackHCILoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCILoadBalancer_To_v1beta2_AzureStackHCILoadBalancer(a.(*AzureStackHCILoadBalancer), b.(*v1beta2.AzureStackHCILoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCILoadBalancerList)(nil), (*AzureStackHCILoadBalancerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList(a.(*v1beta2.AzureStackHCILoadBalancerList), b.(*AzureStackHCILoadBalancerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancerList)(nil), (*v1beta2.AzureStackHCILoadBalancerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCILoadBalancerList_To_v1beta2_AzureStackHCILoadBalancerList(a.(*AzureStackHCILoadBalancerList), b.(*v1beta2.AzureStackHCILoadBalancerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCILoadBalancerStatus)(nil), (*AzureStackHCILoadBalancerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(a.(*v1beta2.AzureStackHCILoadBalancerStatus), b.(*AzureStackHCILoadBalancerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancerStatus)(nil), (*v1beta2.AzureStackHCILoadBalancerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1beta2_AzureStackHCILoadBalancerStatus(a.(*AzureStackHCILoadBalancerStatus), b.(*v1beta2.AzureStackHCILoadBalancerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIMachine)(nil), (*AzureStackHCIMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(a.(*v1beta2.AzureStackHCIMachine), b.(*AzureStackHCIMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachine)(nil), (*v1beta2.AzureStackHCIMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachine_To_v1beta2_AzureStackHCIMachine(a.(*AzureStackHCIMachine), b.(*v1beta2.AzureStackHCIMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIMachineList)(nil), (*AzureStackHCIMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList(a.(*v1beta2.AzureStackHCIMachineList), b.(*AzureStackHCIMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineList)(nil), (*v1beta2.AzureStackHCIMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineList_To_v1beta2_AzureStackHCIMachineList(a.(*AzureStackHCIMachineList), b.(*v1beta2.AzureStackHCIMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIMachineProviderCondition)(nil), (*AzureStackHCIMachineProviderCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition(a.(*v1beta2.AzureStackHCIMachineProviderCondition), b.(*AzureStackHCIMachineProviderCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineProviderCondition)(nil), (*v1beta2.AzureStackHCIMachineProviderCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1beta2_AzureStackHCIMachineProviderCondition(a.(*AzureStackHCIMachineProviderCondition), b.(*v1beta2.AzureStackHCIMachineProviderCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIMachineTemplate)(nil), (*AzureStackHCIMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(a.(*v1beta2.AzureStackHCIMachineTemplate), b.(*AzureStackHCIMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplate)(nil), (*v1beta2.AzureStackHCIMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineTemplate_To_v1beta2_AzureStackHCIMachineTemplate(a.(*AzureStackHCIMachineTemplate), b.(*v1beta2.AzureStackHCIMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIMachineTemplateList)(nil), (*AzureStackHCIMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList(a.(*v1beta2.AzureStackHCIMachineTemplateList), b.(*AzureStackHCIMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateList)(nil), (*v1beta2.AzureStackHCIMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineTemplateList_To_v1beta2_AzureStackHCIMachineTemplateList(a.(*AzureStackHCIMachineTemplateList), b.(*v1beta2.AzureStackHCIMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIMachineTemplateResource)(nil), (*AzureStackHCIMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(a.(*v1beta2.AzureStackHCIMachineTemplateResource), b.(*AzureStackHCIMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateResource)(nil), (*v1beta2.AzureStackHCIMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1beta2_AzureStackHCIMachineTemplateResource(a.(*AzureStackHCIMachineTemplateResource), b.(*v1beta2.AzureStackHCIMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIMachineTemplateSpec)(nil), (*AzureStackHCIMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(a.(*v1beta2.AzureStackHCIMachineTemplateSpec), b.(*AzureStackHCIMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateSpec)(nil), (*v1beta2.AzureStackHCIMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1beta2_AzureStackHCIMachineTemplateSpec(a.(*AzureStackHCIMachineTemplateSpec), b.(*v1beta2.AzureStackHCIMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIResourceReference)(nil), (*AzureStackHCIResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference(a.(*v1beta2.AzureStackHCIResourceReference), b.(*AzureStackHCIResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIResourceReference)(nil), (*v1beta2.AzureStackHCIResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIResourceReference_To_v1beta2_AzureStackHCIResourceReference(a.(*AzureStackHCIResourceReference), b.(*v1beta2.AzureStackHCIResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIVirtualMachine)(nil), (*AzureStackHCIVirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(a.(*v1beta2.AzureStackHCIVirtualMachine), b.(*AzureStackHCIVirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachine)(nil), (*v1beta2.AzureStackHCIVirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIVirtualMachine_To_v1beta2_AzureStackHCIVirtualMachine(a.(*AzureStackHCIVirtualMachine), b.(*v1beta2.AzureStackHCIVirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIVirtualMachineList)(nil), (*AzureStackHCIVirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList(a.(*v1beta2.AzureStackHCIVirtualMachineList), b.(*AzureStackHCIVirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachineList)(nil), (*v1beta2.AzureStackHCIVirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIVirtualMachineList_To_v1beta2_AzureStackHCIVirtualMachineList(a.(*AzureStackHCIVirtualMachineList), b.(*v1beta2.AzureStackHCIVirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AzureStackHCIVirtualMachineStatus)(nil), (*AzureStackHCIVirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(a.(*v1beta2.AzureStackHCIVirtualMachineStatus), b.(*AzureStackHCIVirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachineStatus)(nil), (*v1beta2.AzureStackHCIVirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1beta2_AzureStackHCIVirtualMachineStatus(a.(*AzureStackHCIVirtualMachineStatus), b.(*v1beta2.AzureStackHCIVirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.IpConfigurationSpec)(nil), (*IpConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_IpConfigurationSpec_To_v1beta1_IpConfigurationSpec(a.(*v1beta2.IpConfigurationSpec), b.(*IpConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IpConfigurationSpec)(nil), (*v1beta2.IpConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IpConfigurationSpec_To_v1beta2_IpConfigurationSpec(a.(*IpConfigurationSpec), b.(*v1beta2.IpConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.ManagedDisk)(nil), (*ManagedDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ManagedDisk_To_v1beta1_ManagedDisk(a.(*v1beta2.ManagedDisk), b.(*ManagedDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedDisk)(nil), (*v1beta2.ManagedDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ManagedDisk_To_v1beta2_ManagedDisk(a.(*ManagedDisk), b.(*v1beta2.ManagedDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.NetworkInterfaceSpec)(nil), (*NetworkInterfaceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_NetworkInterfaceSpec_To_v1beta1_NetworkInterfaceSpec(a.(*v1beta2.NetworkInterfaceSpec), b.(*NetworkInterfaceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkInterfaceSpec)(nil), (*v1beta2.NetworkInterfaceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkInterfaceSpec_To_v1beta2_NetworkInterfaceSpec(a.(*NetworkInterfaceSpec), b.(*v1beta2.NetworkInterfaceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_NetworkSpec_To_v1beta1_NetworkSpec(a.(*v1beta2.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSpec)(nil), (*v1beta2.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkSpec_To_v1beta2_NetworkSpec(a.(*NetworkSpec), b.(*v1beta2.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.SubnetSpec)(nil), (*SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_SubnetSpec_To_v1beta1_SubnetSpec(a.(*v1beta2.SubnetSpec), b.(*SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetSpec)(nil), (*v1beta2.SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SubnetSpec_To_v1beta2_SubnetSpec(a.(*SubnetSpec), b.(*v1beta2.SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.VM)(nil), (*VM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_VM_To_v1beta1_VM(a.(*v1beta2.VM), b.(*VM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VM)(nil), (*v1beta2.VM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VM_To_v1beta2_VM(a.(*VM), b.(*v1beta2.VM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.VnetSpec)(nil), (*VnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_VnetSpec_To_v1beta1_VnetSpec(a.(*v1beta2.VnetSpec), b.(*VnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VnetSpec)(nil), (*v1beta2.VnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VnetSpec_To_v1beta2_VnetSpec(a.(*VnetSpec), b.(*v1beta2.VnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*[]*corev1beta1.Condition)(nil), (*[]v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Slice_Pointer_v1beta1_Condition_To_Slice_v1_Condition(a.(*[]*corev1beta1.Condition), b.(*[]v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*[]v1.Condition)(nil), (*[]*corev1beta1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Slice_v1_Condition_To_Slice_Pointer_v1beta1_Condition(a.(*[]v1.Condition), b.(*[]*corev1beta1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Condition)(nil), (*corev1beta1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Condition_To_v1beta1_Condition(a.(*v1.Condition), b.(*corev1beta1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta1.APIEndpoint)(nil), (*corev1beta2.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_APIEndpoint_To_v1beta2_APIEndpoint(a.(*corev1beta1.APIEndpoint), b.(*corev1beta2.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*AvailabilityZone)(nil), (*v1beta2.AvailabilityZone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AvailabilityZone_To_v1beta2_AvailabilityZone(a.(*AvailabilityZone), b.(*v1beta2.AvailabilityZone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*AzureStackHCIClusterStatus)(nil), (*v1beta2.AzureStackHCIClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIClusterStatus_To_v1beta2_AzureStackHCIClusterStatus(a.(*AzureStackHCIClusterStatus), b.(*v1beta2.AzureStackHCIClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*AzureStackHCILoadBalancerSpec)(nil), (*v1beta2.AzureStackHCILoadBalancerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1beta2_AzureStackHCILoadBalancerSpec(a.(*AzureStackHCILoadBalancerSpec), b.(*v1beta2.AzureStackHCILoadBalancerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*AzureStackHCIMachineSpec)(nil), (*v1beta2.AzureStackHCIMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineSpec_To_v1beta2_AzureStackHCIMachineSpec(a.(*AzureStackHCIMachineSpec), b.(*v1beta2.AzureStackHCIMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*AzureStackHCIMachineStatus)(nil), (*v1beta2.AzureStackHCIMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIMachineStatus_To_v1beta2_AzureStackHCIMachineStatus(a.(*AzureStackHCIMachineStatus), b.(*v1beta2.AzureStackHCIMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*AzureStackHCIVirtualMachineSpec)(nil), (*v1beta2.AzureStackHCIVirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1beta2_AzureStackHCIVirtualMachineSpec(a.(*AzureStackHCIVirtualMachineSpec), b.(*v1beta2.AzureStackHCIVirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta1.Condition)(nil), (*v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Condition_To_v1_Condition(a.(*corev1beta1.Condition), b.(*v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Image)(nil), (*v1beta2.Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Image_To_v1beta2_Image(a.(*Image), b.(*v1beta2.Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*OSDisk)(nil), (*v1beta2.OSDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OSDisk_To_v1beta2_OSDisk(a.(*OSDisk), b.(*v1beta2.OSDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta2.APIEndpoint)(nil), (*corev1beta1.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_APIEndpoint_To_v1beta1_APIEndpoint(a.(*corev1beta2.APIEndpoint), b.(*corev1beta1.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.AvailabilityZone)(nil), (*AvailabilityZone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AvailabilityZone_To_v1beta1_AvailabilityZone(a.(*v1beta2.AvailabilityZone), b.(*AvailabilityZone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.AzureStackHCIClusterStatus)(nil), (*AzureStackHCIClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus(a.(*v1beta2.AzureStackHCIClusterStatus), b.(*AzureStackHCIClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.AzureStackHCILoadBalancerSpec)(nil), (*AzureStackHCILoadBalancerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(a.(*v1beta2.AzureStackHCILoadBalancerSpec), b.(*AzureStackHCILoadBalancerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.AzureStackHCIMachineSpec)(nil), (*AzureStackHCIMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(a.(*v1beta2.AzureStackHCIMachineSpec), b.(*AzureStackHCIMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.AzureStackHCIMachineStatus)(nil), (*AzureStackHCIMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus(a.(*v1beta2.AzureStackHCIMachineStatus), b.(*AzureStackHCIMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.AzureStackHCIVirtualMachineSpec)(nil), (*AzureStackHCIVirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec(a.(*v1beta2.AzureStackHCIVirtualMachineSpec), b.(*AzureStackHCIVirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.Image)(nil), (*Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Image_To_v1beta1_Image(a.(*v1beta2.Image), b.(*Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.OSDisk)(nil), (*OSDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OSDisk_To_v1beta1_OSDisk(a.(*v1beta2.OSDisk), b.(*OSDisk), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta2_AvailabilityZone_To_v1beta1_AvailabilityZone(in *v1beta2.AvailabilityZone, out *AvailabilityZone, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

func autoConvert_v1beta1_AvailabilityZone_To_v1beta2_AvailabilityZone(in *AvailabilityZone, out *v1beta2.AvailabilityZone, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

func autoConvert_v1beta2_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(in *v1beta2.AzureStackHCICluster, out *AzureStackHCICluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(in *v1beta2.AzureStackHCICluster, out *AzureStackHCICluster, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCICluster_To_v1beta2_AzureStackHCICluster(in *AzureStackHCICluster, out *v1beta2.AzureStackHCICluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIClusterSpec_To_v1beta2_AzureStackHCIClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_AzureStackHCIClusterStatus_To_v1beta2_AzureStackHCIClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCICluster_To_v1beta2_AzureStackHCICluster is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCICluster_To_v1beta2_AzureStackHCICluster(in *AzureStackHCICluster, out *v1beta2.AzureStackHCICluster, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCICluster_To_v1beta2_AzureStackHCICluster(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList(in *v1beta2.AzureStackHCIClusterList, out *AzureStackHCIClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureStackHCICluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_AzureStackHCICluster_To_v1beta1_AzureStackHCICluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList(in *v1beta2.AzureStackHCIClusterList, out *AzureStackHCIClusterList, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIClusterList_To_v1beta1_AzureStackHCIClusterList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterList_To_v1beta2_AzureStackHCIClusterList(in *AzureStackHCIClusterList, out *v1beta2.AzureStackHCIClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.AzureStackHCICluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_AzureStackHCICluster_To_v1beta2_AzureStackHCICluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterList_To_v1beta2_AzureStackHCIClusterList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterList_To_v1beta2_AzureStackHCIClusterList(in *AzureStackHCIClusterList, out *v1beta2.AzureStackHCIClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterList_To_v1beta2_AzureStackHCIClusterList(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(in *v1beta2.AzureStackHCIClusterSpec, out *AzureStackHCIClusterSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_NetworkSpec_To_v1beta1_NetworkSpec(&in.NetworkSpec, &out.NetworkSpec, s); err != nil {
		return err
	}
	out.ResourceGroup = in.ResourceGroup
	out.Location = in.Location
	if in.AzureStackHCILoadBalancer != nil {
		in, out := &in.AzureStackHCILoadBalancer, &out.AzureStackHCILoadBalancer
		*out = new(AzureStackHCILoadBalancerSpec)
		if err := Convert_v1beta2_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.AzureStackHCILoadBalancer = nil
	}
	if err := Convert_v1beta2_APIEndpoint_To_v1beta1_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.Management = in.Management
	return nil
}

// Convert_v1beta2_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(in *v1beta2.AzureStackHCIClusterSpec, out *AzureStackHCIClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterSpec_To_v1beta2_AzureStackHCIClusterSpec(in *AzureStackHCIClusterSpec, out *v1beta2.AzureStackHCIClusterSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_NetworkSpec_To_v1beta2_NetworkSpec(&in.NetworkSpec, &out.NetworkSpec, s); err != nil {
		return err
	}
	out.ResourceGroup = in.ResourceGroup
	out.Location = in.Location
	if in.AzureStackHCILoadBalancer != nil {
		in, out := &in.AzureStackHCILoadBalancer, &out.AzureStackHCILoadBalancer
		*out = new(v1beta2.AzureStackHCILoadBalancerSpec)
		if err := Convert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1beta2_AzureStackHCILoadBalancerSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.AzureStackHCILoadBalancer = nil
	}
	if err := Convert_v1beta1_APIEndpoint_To_v1beta2_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.Management = in.Management
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterSpec_To_v1beta2_AzureStackHCIClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterSpec_To_v1beta2_AzureStackHCIClusterSpec(in *AzureStackHCIClusterSpec, out *v1beta2.AzureStackHCIClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterSpec_To_v1beta2_AzureStackHCIClusterSpec(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIClusterStatus_To_v1beta1_AzureStackHCIClusterStatus(in *v1beta2.AzureStackHCIClusterStatus, out *AzureStackHCIClusterStatus, s conversion.Scope) error {
	if err := Convert_v1beta2_VM_To_v1beta1_VM(&in.Bastion, &out.Bastion, s); err != nil {
		return err
	}
	out.Phase = in.Phase
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.Initialization requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_AzureStackHCIClusterStatus_To_v1beta2_AzureStackHCIClusterStatus(in *AzureStackHCIClusterStatus, out *v1beta2.AzureStackHCIClusterStatus, s conversion.Scope) error {
	if err := Convert_v1beta1_VM_To_v1beta2_VM(&in.Bastion, &out.Bastion, s); err != nil {
		return err
	}
	// WARNING: in.Ready requires manual conversion: does not exist in peer-type
	out.Phase = in.Phase
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1beta2_AzureStackHCIClusterTemplate_To_v1beta1_AzureStackHCIClusterTemplate(in *v1beta2.AzureStackHCIClusterTemplate, out *AzureStackHCIClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_AzureStackHCIClusterTemplateSpec_To_v1beta1_AzureStackHCIClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIClusterTemplate_To_v1beta1_AzureStackHCIClusterTemplate is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIClusterTemplate_To_v1beta1_AzureStackHCIClusterTemplate(in *v1beta2.AzureStackHCIClusterTemplate, out *AzureStackHCIClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIClusterTemplate_To_v1beta1_AzureStackHCIClusterTemplate(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterTemplate_To_v1beta2_AzureStackHCIClusterTemplate(in *AzureStackHCIClusterTemplate, out *v1beta2.AzureStackHCIClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIClusterTemplateSpec_To_v1beta2_AzureStackHCIClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterTemplate_To_v1beta2_AzureStackHCIClusterTemplate is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterTemplate_To_v1beta2_AzureStackHCIClusterTemplate(in *AzureStackHCIClusterTemplate, out *v1beta2.AzureStackHCIClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterTemplate_To_v1beta2_AzureStackHCIClusterTemplate(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIClusterTemplateList_To_v1beta1_AzureStackHCIClusterTemplateList(in *v1beta2.AzureStackHCIClusterTemplateList, out *AzureStackHCIClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureStackHCIClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_AzureStackHCIClusterTemplate_To_v1beta1_AzureStackHCIClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIClusterTemplateList_To_v1beta1_AzureStackHCIClusterTemplateList is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIClusterTemplateList_To_v1beta1_AzureStackHCIClusterTemplateList(in *v1beta2.AzureStackHCIClusterTemplateList, out *AzureStackHCIClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIClusterTemplateList_To_v1beta1_AzureStackHCIClusterTemplateList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterTemplateList_To_v1beta2_AzureStackHCIClusterTemplateList(in *AzureStackHCIClusterTemplateList, out *v1beta2.AzureStackHCIClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.AzureStackHCIClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_AzureStackHCIClusterTemplate_To_v1beta2_AzureStackHCIClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterTemplateList_To_v1beta2_AzureStackHCIClusterTemplateList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterTemplateList_To_v1beta2_AzureStackHCIClusterTemplateList(in *AzureStackHCIClusterTemplateList, out *v1beta2.AzureStackHCIClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterTemplateList_To_v1beta2_AzureStackHCIClusterTemplateList(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIClusterTemplateResource_To_v1beta1_AzureStackHCIClusterTemplateResource(in *v1beta2.AzureStackHCIClusterTemplateResource, out *AzureStackHCIClusterTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta2_AzureStackHCIClusterSpec_To_v1beta1_AzureStackHCIClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIClusterTemplateResource_To_v1beta1_AzureStackHCIClusterTemplateResource is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIClusterTemplateResource_To_v1beta1_AzureStackHCIClusterTemplateResource(in *v1beta2.AzureStackHCIClusterTemplateResource, out *AzureStackHCIClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIClusterTemplateResource_To_v1beta1_AzureStackHCIClusterTemplateResource(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterTemplateResource_To_v1beta2_AzureStackHCIClusterTemplateResource(in *AzureStackHCIClusterTemplateResource, out *v1beta2.AzureStackHCIClusterTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_AzureStackHCIClusterSpec_To_v1beta2_AzureStackHCIClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterTemplateResource_To_v1beta2_AzureStackHCIClusterTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterTemplateResource_To_v1beta2_AzureStackHCIClusterTemplateResource(in *AzureStackHCIClusterTemplateResource, out *v1beta2.AzureStackHCIClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterTemplateResource_To_v1beta2_AzureStackHCIClusterTemplateResource(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIClusterTemplateSpec_To_v1beta1_AzureStackHCIClusterTemplateSpec(in *v1beta2.AzureStackHCIClusterTemplateSpec, out *AzureStackHCIClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_AzureStackHCIClusterTemplateResource_To_v1beta1_AzureStackHCIClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIClusterTemplateSpec_To_v1beta1_AzureStackHCIClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIClusterTemplateSpec_To_v1beta1_AzureStackHCIClusterTemplateSpec(in *v1beta2.AzureStackHCIClusterTemplateSpec, out *AzureStackHCIClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIClusterTemplateSpec_To_v1beta1_AzureStackHCIClusterTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIClusterTemplateSpec_To_v1beta2_AzureStackHCIClusterTemplateSpec(in *AzureStackHCIClusterTemplateSpec, out *v1beta2.AzureStackHCIClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_AzureStackHCIClusterTemplateResource_To_v1beta2_AzureStackHCIClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIClusterTemplateSpec_To_v1beta2_AzureStackHCIClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIClusterTemplateSpec_To_v1beta2_AzureStackHCIClusterTemplateSpec(in *AzureStackHCIClusterTemplateSpec, out *v1beta2.AzureStackHCIClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIClusterTemplateSpec_To_v1beta2_AzureStackHCIClusterTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(in *v1beta2.AzureStackHCILoadBalancer, out *AzureStackHCILoadBalancer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(in *v1beta2.AzureStackHCILoadBalancer, out *AzureStackHCILoadBalancer, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCILoadBalancer_To_v1beta2_AzureStackHCILoadBalancer(in *AzureStackHCILoadBalancer, out *v1beta2.AzureStackHCILoadBalancer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1beta2_AzureStackHCILoadBalancerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1beta2_AzureStackHCILoadBalancerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCILoadBalancer_To_v1beta2_AzureStackHCILoadBalancer is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCILoadBalancer_To_v1beta2_AzureStackHCILoadBalancer(in *AzureStackHCILoadBalancer, out *v1beta2.AzureStackHCILoadBalancer, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCILoadBalancer_To_v1beta2_AzureStackHCILoadBalancer(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList(in *v1beta2.AzureStackHCILoadBalancerList, out *AzureStackHCILoadBalancerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureStackHCILoadBalancer, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_AzureStackHCILoadBalancer_To_v1beta1_AzureStackHCILoadBalancer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList(in *v1beta2.AzureStackHCILoadBalancerList, out *AzureStackHCILoadBalancerList, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCILoadBalancerList_To_v1beta1_AzureStackHCILoadBalancerList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCILoadBalancerList_To_v1beta2_AzureStackHCILoadBalancerList(in *AzureStackHCILoadBalancerList, out *v1beta2.AzureStackHCILoadBalancerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.AzureStackHCILoadBalancer, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_AzureStackHCILoadBalancer_To_v1beta2_AzureStackHCILoadBalancer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_AzureStackHCILoadBalancerList_To_v1beta2_AzureStackHCILoadBalancerList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCILoadBalancerList_To_v1beta2_AzureStackHCILoadBalancerList(in *AzureStackHCILoadBalancerList, out *v1beta2.AzureStackHCILoadBalancerList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCILoadBalancerList_To_v1beta2_AzureStackHCILoadBalancerList(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCILoadBalancerSpec_To_v1beta1_AzureStackHCILoadBalancerSpec(in *v1beta2.AzureStackHCILoadBalancerSpec, out *AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	out.SSHPublicKey = in.SSHPublicKey
	// WARNING: in.Image requires manual conversion: inconvertible types (*github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.Image vs github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.Image)
	out.VMSize = in.VMSize
	out.StorageContainer = in.StorageContainer
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

func autoConvert_v1beta1_AzureStackHCILoadBalancerSpec_To_v1beta2_AzureStackHCILoadBalancerSpec(in *AzureStackHCILoadBalancerSpec, out *v1beta2.AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	out.SSHPublicKey = in.SSHPublicKey
	// WARNING: in.Image requires manual conversion: inconvertible types (github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.Image vs *github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.Image)
	out.VMSize = in.VMSize
	out.StorageContainer = in.StorageContainer
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

func autoConvert_v1beta2_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(in *v1beta2.AzureStackHCILoadBalancerStatus, out *AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.ReadyReplicas = in.ReadyReplicas
	out.FailedReplicas = in.FailedReplicas
	out.Address = in.Address
	out.Port = in.Port
	out.Phase = in.Phase
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	out.ErrorReason = (*errors.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.Selector = in.Selector
	return nil
}

// Convert_v1beta2_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(in *v1beta2.AzureStackHCILoadBalancerStatus, out *AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCILoadBalancerStatus_To_v1beta1_AzureStackHCILoadBalancerStatus(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1beta2_AzureStackHCILoadBalancerStatus(in *AzureStackHCILoadBalancerStatus, out *v1beta2.AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.ReadyReplicas = in.ReadyReplicas
	out.FailedReplicas = in.FailedReplicas
	out.Address = in.Address
	out.Port = in.Port
	out.Phase = in.Phase
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	out.ErrorReason = (*errors.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.Selector = in.Selector
	return nil
}

// Convert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1beta2_AzureStackHCILoadBalancerStatus is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1beta2_AzureStackHCILoadBalancerStatus(in *AzureStackHCILoadBalancerStatus, out *v1beta2.AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCILoadBalancerStatus_To_v1beta2_AzureStackHCILoadBalancerStatus(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(in *v1beta2.AzureStackHCIMachine, out *AzureStackHCIMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(in *v1beta2.AzureStackHCIMachine, out *AzureStackHCIMachine, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachine_To_v1beta2_AzureStackHCIMachine(in *AzureStackHCIMachine, out *v1beta2.AzureStackHCIMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIMachineSpec_To_v1beta2_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_AzureStackHCIMachineStatus_To_v1beta2_AzureStackHCIMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachine_To_v1beta2_AzureStackHCIMachine is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachine_To_v1beta2_AzureStackHCIMachine(in *AzureStackHCIMachine, out *v1beta2.AzureStackHCIMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachine_To_v1beta2_AzureStackHCIMachine(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList(in *v1beta2.AzureStackHCIMachineList, out *AzureStackHCIMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureStackHCIMachine, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_AzureStackHCIMachine_To_v1beta1_AzureStackHCIMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList(in *v1beta2.AzureStackHCIMachineList, out *AzureStackHCIMachineList, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIMachineList_To_v1beta1_AzureStackHCIMachineList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineList_To_v1beta2_AzureStackHCIMachineList(in *AzureStackHCIMachineList, out *v1beta2.AzureStackHCIMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.AzureStackHCIMachine, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_AzureStackHCIMachine_To_v1beta2_AzureStackHCIMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineList_To_v1beta2_AzureStackHCIMachineList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineList_To_v1beta2_AzureStackHCIMachineList(in *AzureStackHCIMachineList, out *v1beta2.AzureStackHCIMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineList_To_v1beta2_AzureStackHCIMachineList(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition(in *v1beta2.AzureStackHCIMachineProviderCondition, out *AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	out.Type = AzureStackHCIMachineProviderConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1beta2_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition(in *v1beta2.AzureStackHCIMachineProviderCondition, out *AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIMachineProviderCondition_To_v1beta1_AzureStackHCIMachineProviderCondition(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1beta2_AzureStackHCIMachineProviderCondition(in *AzureStackHCIMachineProviderCondition, out *v1beta2.AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	out.Type = v1beta2.AzureStackHCIMachineProviderConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1beta2_AzureStackHCIMachineProviderCondition is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1beta2_AzureStackHCIMachineProviderCondition(in *AzureStackHCIMachineProviderCondition, out *v1beta2.AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineProviderCondition_To_v1beta2_AzureStackHCIMachineProviderCondition(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(in *v1beta2.AzureStackHCIMachineSpec, out *AzureStackHCIMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VMSize = in.VMSize
	// WARNING: in.AvailabilityZone requires manual conversion: inconvertible types (*github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.AvailabilityZone vs github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.AvailabilityZone)
	// WARNING: in.Image requires manual conversion: inconvertible types (*github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.Image vs github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.Image)
	// WARNING: in.OSDisk requires manual conversion: inconvertible types (*github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.OSDisk vs github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.OSDisk)
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.StorageContainer = in.StorageContainer
	out.GpuCount = in.GpuCount
	out.AllocatePublicIP = in.AllocatePublicIP
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	out.NetworkInterfaces = *(*NetworkInterfaces)(unsafe.Pointer(&in.NetworkInterfaces))
	out.AvailabilitySetName = in.AvailabilitySetName
	out.PlacementGroupName = in.PlacementGroupName
	return nil
}

func autoConvert_v1beta1_AzureStackHCIMachineSpec_To_v1beta2_AzureStackHCIMachineSpec(in *AzureStackHCIMachineSpec, out *v1beta2.AzureStackHCIMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VMSize = in.VMSize
	// WARNING: in.AvailabilityZone requires manual conversion: inconvertible types (github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.AvailabilityZone vs *github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.AvailabilityZone)
	// WARNING: in.Image requires manual conversion: inconvertible types (github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.Image vs *github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.Image)
	// WARNING: in.OSDisk requires manual conversion: inconvertible types (github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.OSDisk vs *github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.OSDisk)
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.StorageContainer = in.StorageContainer
	out.GpuCount = in.GpuCount
	out.AllocatePublicIP = in.AllocatePublicIP
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	out.NetworkInterfaces = *(*v1beta2.NetworkInterfaces)(unsafe.Pointer(&in.NetworkInterfaces))
	out.AvailabilitySetName = in.AvailabilitySetName
	out.PlacementGroupName = in.PlacementGroupName
	return nil
}

func autoConvert_v1beta2_AzureStackHCIMachineStatus_To_v1beta1_AzureStackHCIMachineStatus(in *v1beta2.AzureStackHCIMachineStatus, out *AzureStackHCIMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]corev1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*VMState)(unsafe.Pointer(in.VMState))
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.Initialization requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_AzureStackHCIMachineStatus_To_v1beta2_AzureStackHCIMachineStatus(in *AzureStackHCIMachineStatus, out *v1beta2.AzureStackHCIMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]corev1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*v1beta2.VMState)(unsafe.Pointer(in.VMState))
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(in *v1beta2.AzureStackHCIMachineTemplate, out *AzureStackHCIMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(in *v1beta2.AzureStackHCIMachineTemplate, out *AzureStackHCIMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineTemplate_To_v1beta2_AzureStackHCIMachineTemplate(in *AzureStackHCIMachineTemplate, out *v1beta2.AzureStackHCIMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1beta2_AzureStackHCIMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineTemplate_To_v1beta2_AzureStackHCIMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineTemplate_To_v1beta2_AzureStackHCIMachineTemplate(in *AzureStackHCIMachineTemplate, out *v1beta2.AzureStackHCIMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineTemplate_To_v1beta2_AzureStackHCIMachineTemplate(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList(in *v1beta2.AzureStackHCIMachineTemplateList, out *AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureStackHCIMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_AzureStackHCIMachineTemplate_To_v1beta1_AzureStackHCIMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList(in *v1beta2.AzureStackHCIMachineTemplateList, out *AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIMachineTemplateList_To_v1beta1_AzureStackHCIMachineTemplateList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineTemplateList_To_v1beta2_AzureStackHCIMachineTemplateList(in *AzureStackHCIMachineTemplateList, out *v1beta2.AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.AzureStackHCIMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_AzureStackHCIMachineTemplate_To_v1beta2_AzureStackHCIMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineTemplateList_To_v1beta2_AzureStackHCIMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineTemplateList_To_v1beta2_AzureStackHCIMachineTemplateList(in *AzureStackHCIMachineTemplateList, out *v1beta2.AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineTemplateList_To_v1beta2_AzureStackHCIMachineTemplateList(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(in *v1beta2.AzureStackHCIMachineTemplateResource, out *AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta2_AzureStackHCIMachineSpec_To_v1beta1_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(in *v1beta2.AzureStackHCIMachineTemplateResource, out *AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1beta2_AzureStackHCIMachineTemplateResource(in *AzureStackHCIMachineTemplateResource, out *v1beta2.AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_AzureStackHCIMachineSpec_To_v1beta2_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1beta2_AzureStackHCIMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1beta2_AzureStackHCIMachineTemplateResource(in *AzureStackHCIMachineTemplateResource, out *v1beta2.AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1beta2_AzureStackHCIMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(in *v1beta2.AzureStackHCIMachineTemplateSpec, out *AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_AzureStackHCIMachineTemplateResource_To_v1beta1_AzureStackHCIMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(in *v1beta2.AzureStackHCIMachineTemplateSpec, out *AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIMachineTemplateSpec_To_v1beta1_AzureStackHCIMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1beta2_AzureStackHCIMachineTemplateSpec(in *AzureStackHCIMachineTemplateSpec, out *v1beta2.AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_AzureStackHCIMachineTemplateResource_To_v1beta2_AzureStackHCIMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1beta2_AzureStackHCIMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1beta2_AzureStackHCIMachineTemplateSpec(in *AzureStackHCIMachineTemplateSpec, out *v1beta2.AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIMachineTemplateSpec_To_v1beta2_AzureStackHCIMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference(in *v1beta2.AzureStackHCIResourceReference, out *AzureStackHCIResourceReference, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	return nil
}

// Convert_v1beta2_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference(in *v1beta2.AzureStackHCIResourceReference, out *AzureStackHCIResourceReference, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIResourceReference_To_v1beta1_AzureStackHCIResourceReference(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIResourceReference_To_v1beta2_AzureStackHCIResourceReference(in *AzureStackHCIResourceReference, out *v1beta2.AzureStackHCIResourceReference, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	return nil
}

// Convert_v1beta1_AzureStackHCIResourceReference_To_v1beta2_AzureStackHCIResourceReference is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIResourceReference_To_v1beta2_AzureStackHCIResourceReference(in *AzureStackHCIResourceReference, out *v1beta2.AzureStackHCIResourceReference, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIResourceReference_To_v1beta2_AzureStackHCIResourceReference(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(in *v1beta2.AzureStackHCIVirtualMachine, out *AzureStackHCIVirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(in *v1beta2.AzureStackHCIVirtualMachine, out *AzureStackHCIVirtualMachine, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIVirtualMachine_To_v1beta2_AzureStackHCIVirtualMachine(in *AzureStackHCIVirtualMachine, out *v1beta2.AzureStackHCIVirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1beta2_AzureStackHCIVirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1beta2_AzureStackHCIVirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIVirtualMachine_To_v1beta2_AzureStackHCIVirtualMachine is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIVirtualMachine_To_v1beta2_AzureStackHCIVirtualMachine(in *AzureStackHCIVirtualMachine, out *v1beta2.AzureStackHCIVirtualMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIVirtualMachine_To_v1beta2_AzureStackHCIVirtualMachine(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList(in *v1beta2.AzureStackHCIVirtualMachineList, out *AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureStackHCIVirtualMachine, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_AzureStackHCIVirtualMachine_To_v1beta1_AzureStackHCIVirtualMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList(in *v1beta2.AzureStackHCIVirtualMachineList, out *AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIVirtualMachineList_To_v1beta1_AzureStackHCIVirtualMachineList(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIVirtualMachineList_To_v1beta2_AzureStackHCIVirtualMachineList(in *AzureStackHCIVirtualMachineList, out *v1beta2.AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.AzureStackHCIVirtualMachine, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_AzureStackHCIVirtualMachine_To_v1beta2_AzureStackHCIVirtualMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIVirtualMachineList_To_v1beta2_AzureStackHCIVirtualMachineList is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIVirtualMachineList_To_v1beta2_AzureStackHCIVirtualMachineList(in *AzureStackHCIVirtualMachineList, out *v1beta2.AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIVirtualMachineList_To_v1beta2_AzureStackHCIVirtualMachineList(in, out, s)
}

func autoConvert_v1beta2_AzureStackHCIVirtualMachineSpec_To_v1beta1_AzureStackHCIVirtualMachineSpec(in *v1beta2.AzureStackHCIVirtualMachineSpec, out *AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	out.VMSize = in.VMSize
	// WARNING: in.AvailabilityZone requires manual conversion: inconvertible types (*github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.AvailabilityZone vs github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.AvailabilityZone)
	// WARNING: in.Image requires manual conversion: inconvertible types (*github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.Image vs github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.Image)
	// WARNING: in.OSDisk requires manual conversion: inconvertible types (*github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.OSDisk vs github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.OSDisk)
	out.BootstrapData = (*string)(unsafe.Pointer(in.BootstrapData))
	out.Identity = VMIdentity(in.Identity)
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.StorageContainer = in.StorageContainer
	out.GpuCount = in.GpuCount
	out.ResourceGroup = in.ResourceGroup
	out.VnetName = in.VnetName
	out.ClusterName = in.ClusterName
	out.SubnetName = in.SubnetName
	out.BackendPoolNames = *(*[]string)(unsafe.Pointer(&in.BackendPoolNames))
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	out.NetworkInterfaces = *(*NetworkInterfaces)(unsafe.Pointer(&in.NetworkInterfaces))
	out.AvailabilitySetName = in.AvailabilitySetName
	out.PlacementGroupName = in.PlacementGroupName
	return nil
}

func autoConvert_v1beta1_AzureStackHCIVirtualMachineSpec_To_v1beta2_AzureStackHCIVirtualMachineSpec(in *AzureStackHCIVirtualMachineSpec, out *v1beta2.AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	out.VMSize = in.VMSize
	// WARNING: in.AvailabilityZone requires manual conversion: inconvertible types (github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.AvailabilityZone vs *github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.AvailabilityZone)
	// WARNING: in.Image requires manual conversion: inconvertible types (github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.Image vs *github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.Image)
	// WARNING: in.OSDisk requires manual conversion: inconvertible types (github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.OSDisk vs *github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.OSDisk)
	out.BootstrapData = (*string)(unsafe.Pointer(in.BootstrapData))
	out.Identity = v1beta2.VMIdentity(in.Identity)
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.StorageContainer = in.StorageContainer
	out.GpuCount = in.GpuCount
	out.ResourceGroup = in.ResourceGroup
	out.VnetName = in.VnetName
	out.ClusterName = in.ClusterName
	out.SubnetName = in.SubnetName
	out.BackendPoolNames = *(*[]string)(unsafe.Pointer(&in.BackendPoolNames))
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	out.NetworkInterfaces = *(*v1beta2.NetworkInterfaces)(unsafe.Pointer(&in.NetworkInterfaces))
	out.AvailabilitySetName = in.AvailabilitySetName
	out.PlacementGroupName = in.PlacementGroupName
	return nil
}

func autoConvert_v1beta2_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(in *v1beta2.AzureStackHCIVirtualMachineStatus, out *AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]corev1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*VMState)(unsafe.Pointer(in.VMState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

// Convert_v1beta2_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus is an autogenerated conversion function.
func Convert_v1beta2_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(in *v1beta2.AzureStackHCIVirtualMachineStatus, out *AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_AzureStackHCIVirtualMachineStatus_To_v1beta1_AzureStackHCIVirtualMachineStatus(in, out, s)
}

func autoConvert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1beta2_AzureStackHCIVirtualMachineStatus(in *AzureStackHCIVirtualMachineStatus, out *v1beta2.AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]corev1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*v1beta2.VMState)(unsafe.Pointer(in.VMState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

// Convert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1beta2_AzureStackHCIVirtualMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1beta2_AzureStackHCIVirtualMachineStatus(in *AzureStackHCIVirtualMachineStatus, out *v1beta2.AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_AzureStackHCIVirtualMachineStatus_To_v1beta2_AzureStackHCIVirtualMachineStatus(in, out, s)
}

func autoConvert_v1beta2_Image_To_v1beta1_Image(in *v1beta2.Image, out *Image, s conversion.Scope) error {
	out.Publisher = (*string)(unsafe.Pointer(in.Publisher))
	out.Offer = (*string)(unsafe.Pointer(in.Offer))
	out.SKU = (*string)(unsafe.Pointer(in.SKU))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.SubscriptionID = (*string)(unsafe.Pointer(in.SubscriptionID))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.Gallery = (*string)(unsafe.Pointer(in.Gallery))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.OSType = OSType(in.OSType)
	return nil
}

func autoConvert_v1beta1_Image_To_v1beta2_Image(in *Image, out *v1beta2.Image, s conversion.Scope) error {
	out.Publisher = (*string)(unsafe.Pointer(in.Publisher))
	out.Offer = (*string)(unsafe.Pointer(in.Offer))
	out.SKU = (*string)(unsafe.Pointer(in.SKU))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.SubscriptionID = (*string)(unsafe.Pointer(in.SubscriptionID))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.Gallery = (*string)(unsafe.Pointer(in.Gallery))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.OSType = v1beta2.OSType(in.OSType)
	return nil
}

func autoConvert_v1beta2_IpConfigurationSpec_To_v1beta1_IpConfigurationSpec(in *v1beta2.IpConfigurationSpec, out *IpConfigurationSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Primary = in.Primary
	out.Allocation = IPAllocationMethod(in.Allocation)
	out.IpAddress = in.IpAddress
	out.PrefixLength = in.PrefixLength
	out.SubnetId = in.SubnetId
	out.Gateway = in.Gateway
	return nil
}

// Convert_v1beta2_IpConfigurationSpec_To_v1beta1_IpConfigurationSpec is an autogenerated conversion function.
func Convert_v1beta2_IpConfigurationSpec_To_v1beta1_IpConfigurationSpec(in *v1beta2.IpConfigurationSpec, out *IpConfigurationSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_IpConfigurationSpec_To_v1beta1_IpConfigurationSpec(in, out, s)
}

func autoConvert_v1beta1_IpConfigurationSpec_To_v1beta2_IpConfigurationSpec(in *IpConfigurationSpec, out *v1beta2.IpConfigurationSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Primary = in.Primary
	out.Allocation = v1beta2.IPAllocationMethod(in.Allocation)
	out.IpAddress = in.IpAddress
	out.PrefixLength = in.PrefixLength
	out.SubnetId = in.SubnetId
	out.Gateway = in.Gateway
	return nil
}

// Convert_v1beta1_IpConfigurationSpec_To_v1beta2_IpConfigurationSpec is an autogenerated conversion function.
func Convert_v1beta1_IpConfigurationSpec_To_v1beta2_IpConfigurationSpec(in *IpConfigurationSpec, out *v1beta2.IpConfigurationSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_IpConfigurationSpec_To_v1beta2_IpConfigurationSpec(in, out, s)
}

func autoConvert_v1beta2_ManagedDisk_To_v1beta1_ManagedDisk(in *v1beta2.ManagedDisk, out *ManagedDisk, s conversion.Scope) error {
	out.StorageAccountType = in.StorageAccountType
	return nil
}

// Convert_v1beta2_ManagedDisk_To_v1beta1_ManagedDisk is an autogenerated conversion function.
func Convert_v1beta2_ManagedDisk_To_v1beta1_ManagedDisk(in *v1beta2.ManagedDisk, out *ManagedDisk, s conversion.Scope) error {
	return autoConvert_v1beta2_ManagedDisk_To_v1beta1_ManagedDisk(in, out, s)
}

func autoConvert_v1beta1_ManagedDisk_To_v1beta2_ManagedDisk(in *ManagedDisk, out *v1beta2.ManagedDisk, s conversion.Scope) error {
	out.StorageAccountType = in.StorageAccountType
	return nil
}

// Convert_v1beta1_ManagedDisk_To_v1beta2_ManagedDisk is an autogenerated conversion function.
func Convert_v1beta1_ManagedDisk_To_v1beta2_ManagedDisk(in *ManagedDisk, out *v1beta2.ManagedDisk, s conversion.Scope) error {
	return autoConvert_v1beta1_ManagedDisk_To_v1beta2_ManagedDisk(in, out, s)
}

func autoConvert_v1beta2_NetworkInterfaceSpec_To_v1beta1_NetworkInterfaceSpec(in *v1beta2.NetworkInterfaceSpec, out *NetworkInterfaceSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.IPConfigurations = *(*IpConfigurations)(unsafe.Pointer(&in.IPConfigurations))
	return nil
}

// Convert_v1beta2_NetworkInterfaceSpec_To_v1beta1_NetworkInterfaceSpec is an autogenerated conversion function.
func Convert_v1beta2_NetworkInterfaceSpec_To_v1beta1_NetworkInterfaceSpec(in *v1beta2.NetworkInterfaceSpec, out *NetworkInterfaceSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_NetworkInterfaceSpec_To_v1beta1_NetworkInterfaceSpec(in, out, s)
}

func autoConvert_v1beta1_NetworkInterfaceSpec_To_v1beta2_NetworkInterfaceSpec(in *NetworkInterfaceSpec, out *v1beta2.NetworkInterfaceSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.IPConfigurations = *(*v1beta2.IpConfigurations)(unsafe.Pointer(&in.IPConfigurations))
	return nil
}

// Convert_v1beta1_NetworkInterfaceSpec_To_v1beta2_NetworkInterfaceSpec is an autogenerated conversion function.
func Convert_v1beta1_NetworkInterfaceSpec_To_v1beta2_NetworkInterfaceSpec(in *NetworkInterfaceSpec, out *v1beta2.NetworkInterfaceSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkInterfaceSpec_To_v1beta2_NetworkInterfaceSpec(in, out, s)
}

func autoConvert_v1beta2_NetworkSpec_To_v1beta1_NetworkSpec(in *v1beta2.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_VnetSpec_To_v1beta1_VnetSpec(&in.Vnet, &out.Vnet, s); err != nil {
		return err
	}
	out.Subnets = *(*Subnets)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1beta2_NetworkSpec_To_v1beta1_NetworkSpec is an autogenerated conversion function.
func Convert_v1beta2_NetworkSpec_To_v1beta1_NetworkSpec(in *v1beta2.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_NetworkSpec_To_v1beta1_NetworkSpec(in, out, s)
}

func autoConvert_v1beta1_NetworkSpec_To_v1beta2_NetworkSpec(in *NetworkSpec, out *v1beta2.NetworkSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_VnetSpec_To_v1beta2_VnetSpec(&in.Vnet, &out.Vnet, s); err != nil {
		return err
	}
	out.Subnets = *(*v1beta2.Subnets)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1beta1_NetworkSpec_To_v1beta2_NetworkSpec is an autogenerated conversion function.
func Convert_v1beta1_NetworkSpec_To_v1beta2_NetworkSpec(in *NetworkSpec, out *v1beta2.NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkSpec_To_v1beta2_NetworkSpec(in, out, s)
}

func autoConvert_v1beta2_OSDisk_To_v1beta1_OSDisk(in *v1beta2.OSDisk, out *OSDisk, s conversion.Scope) error {
	out.Name = in.Name
	out.Source = in.Source
	out.OSType = OSType(in.OSType)
	out.DiskSizeGB = in.DiskSizeGB
	// WARNING: in.ManagedDisk requires manual conversion: inconvertible types (*github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.ManagedDisk vs github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.ManagedDisk)
	return nil
}

func autoConvert_v1beta1_OSDisk_To_v1beta2_OSDisk(in *OSDisk, out *v1beta2.OSDisk, s conversion.Scope) error {
	out.Name = in.Name
	out.Source = in.Source
	out.OSType = v1beta2.OSType(in.OSType)
	out.DiskSizeGB = in.DiskSizeGB
	// WARNING: in.ManagedDisk requires manual conversion: inconvertible types (github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta1.ManagedDisk vs *github.com/microsoft/cluster-api-provider-azurestackhci/api/v1beta2.ManagedDisk)
	return nil
}

func autoConvert_v1beta2_SubnetSpec_To_v1beta1_SubnetSpec(in *v1beta2.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.VnetID = in.VnetID
	out.CidrBlock = in.CidrBlock
	return nil
}

// Convert_v1beta2_SubnetSpec_To_v1beta1_SubnetSpec is an autogenerated conversion function.
func Convert_v1beta2_SubnetSpec_To_v1beta1_SubnetSpec(in *v1beta2.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_SubnetSpec_To_v1beta1_SubnetSpec(in, out, s)
}

func autoConvert_v1beta1_SubnetSpec_To_v1beta2_SubnetSpec(in *SubnetSpec, out *v1beta2.SubnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.VnetID = in.VnetID
	out.CidrBlock = in.CidrBlock
	return nil
}

// Convert_v1beta1_SubnetSpec_To_v1beta2_SubnetSpec is an autogenerated conversion function.
func Convert_v1beta1_SubnetSpec_To_v1beta2_SubnetSpec(in *SubnetSpec, out *v1beta2.SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SubnetSpec_To_v1beta2_SubnetSpec(in, out, s)
}

func autoConvert_v1beta2_VM_To_v1beta1_VM(in *v1beta2.VM, out *VM, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.AvailabilityZone = in.AvailabilityZone
	out.VMSize = in.VMSize
	if err := Convert_v1beta2_Image_To_v1beta1_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OSDisk_To_v1beta1_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = in.BootstrapData
	out.State = VMState(in.State)
	out.Identity = VMIdentity(in.Identity)
	return nil
}

// Convert_v1beta2_VM_To_v1beta1_VM is an autogenerated conversion function.
func Convert_v1beta2_VM_To_v1beta1_VM(in *v1beta2.VM, out *VM, s conversion.Scope) error {
	return autoConvert_v1beta2_VM_To_v1beta1_VM(in, out, s)
}

func autoConvert_v1beta1_VM_To_v1beta2_VM(in *VM, out *v1beta2.VM, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.AvailabilityZone = in.AvailabilityZone
	out.VMSize = in.VMSize
	if err := Convert_v1beta1_Image_To_v1beta2_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OSDisk_To_v1beta2_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = in.BootstrapData
	out.State = v1beta2.VMState(in.State)
	out.Identity = v1beta2.VMIdentity(in.Identity)
	return nil
}

// Convert_v1beta1_VM_To_v1beta2_VM is an autogenerated conversion function.
func Convert_v1beta1_VM_To_v1beta2_VM(in *VM, out *v1beta2.VM, s conversion.Scope) error {
	return autoConvert_v1beta1_VM_To_v1beta2_VM(in, out, s)
}

func autoConvert_v1beta2_VnetSpec_To_v1beta1_VnetSpec(in *v1beta2.VnetSpec, out *VnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.CidrBlock = in.CidrBlock
	out.Group = in.Group
	return nil
}

// Convert_v1beta2_VnetSpec_To_v1beta1_VnetSpec is an autogenerated conversion function.
func Convert_v1beta2_VnetSpec_To_v1beta1_VnetSpec(in *v1beta2.VnetSpec, out *VnetSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_VnetSpec_To_v1beta1_VnetSpec(in, out, s)
}

func autoConvert_v1beta1_VnetSpec_To_v1beta2_VnetSpec(in *VnetSpec, out *v1beta2.VnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.CidrBlock = in.CidrBlock
	out.Group = in.Group
	return nil
}

// Convert_v1beta1_VnetSpec_To_v1beta2_VnetSpec is an autogenerated conversion function.
func Convert_v1beta1_VnetSpec_To_v1beta2_VnetSpec(in *VnetSpec, out *v1beta2.VnetSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VnetSpec_To_v1beta2_VnetSpec(in, out, s)
}
