---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["${AZURESTACKHCI_POD_CIDR}"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureStackHCICluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "${CLUSTER_NAME}-control-plane"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureStackHCICluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  resourceGroup: "${AZURESTACKHCI_CLUSTER_RESOURCE_GROUP}"
  location: "westus"
  networkSpec:
    vnet:
      name: "${AZURESTACKHCI_VNET_NAME}"
  loadBalancer:
    sshPublicKey: ${AZURESTACKHCI_SSH_PUBLIC_KEY}
    vmSize: "${AZURESTACKHCI_LOAD_BALANCER_MACHINE_TYPE}"
  version: "${KUBERNETES_VERSION}"
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  infrastructureTemplate:
    kind: AzureStackHCIMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    name: "${CLUSTER_NAME}-control-plane"
  kubeadmConfigSpec:
    useExperimentalRetryJoin: true
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        kubeletExtraArgs:
          anonymous-auth: "false"
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
    clusterConfiguration:
      apiServer:
        timeoutForControlPlane: 20m
      controllerManager:
        extraArgs:
          terminated-pod-gc-threshold: "10"
          bind-address: "0.0.0.0"
      scheduler:
        extraArgs:
          bind-address: "0.0.0.0"
    preKubeadmCommands:
    - bash -c /tmp/kubeadm-bootstrap.sh
    postKubeadmCommands:
    - bash -c /tmp/kubeadm-postinstall.sh
    files:
    - path: /etc/rc.d/init.d/azurestackhci_boot.sh
      owner: root:root
      permissions: '0755'
      content: |
        #!/bin/bash
        iptables-restore -v -w < /etc/sysconfig/iptables
    - path: /etc/systemd/system/azurestackhci_boot.service
      owner: root:root
      permissions: '0644'
      content: |
        [Unit]
        Description=azurestackhci_boot
        After=network.target
        
        [Service]
        Type=simple
        ExecStart=/etc/rc.d/init.d/azurestackhci_boot.sh
        TimeoutStartSec=0
        
        [Install]
        WantedBy=default.target
    - path: /etc/kubernetes/cni/win-kube-proxy.yaml
      owner: "root:root"
      permissions: "0744"
      content: |
        ---
        apiVersion: v1
        data:
          run-script.ps1: |-
            $ErrorActionPreference = "Stop";
            mkdir -force /host/var/lib/kube-proxy/var/run/secrets/kubernetes.io/serviceaccount
            mkdir -force /host/kube-proxy
            cp -force /kube-proxy/* /host/kube-proxy
            cp -force /var/lib/kube-proxy/* /host/var/lib/kube-proxy
            cp -force /var/run/secrets/kubernetes.io/serviceaccount/* /host/var/lib/kube-proxy/var/run/secrets/kubernetes.io/serviceaccount #FIXME?
            $networkName = (Get-Content /host/etc/cni/net.d/* | ConvertFrom-Json).name
            $sourceVip = ($env:POD_IP -split "\.")[0..2] + 0 -join "."
            $filePath="/host/var/lib/kube-proxy/config.conf"
            $tempFilePath="/host/var/lib/kube-proxy/configCopy.conf"

            $find = get-content $filePath | ForEach-Object -Process {if($_.Contains("sourceVip:")) {$_}}
            $replace = "  sourceVip: " + $sourceVip
            if ($find) {
                (Get-Content -Path $filePath) -replace $find, $replace | Add-Content $tempFilePath
            } else {
                $replace = "winkernel:`r`n  sourceVip:" + $sourceVip + "`r`n"
                $find = get-content $filePath | ForEach-Object -Process {if($_.Contains("winkernel:")) {$_}}
                if ($find) {
                    (Get-Content -Path $filePath) -replace $find, $replace | Add-Content $tempFilePath    
                } else {
                    (Get-Content -Path $filePath) + $replace | Add-Content $tempFilePath
                }    
            }
            Remove-Item -Path $filePath
            Move-Item -Path $tempFilePath -Destination $filePath

            $find = get-content $filePath | ForEach-Object -Process {if($_.Contains("networkName:")) {$_}}
            $replace = "  networkName: " + $networkName
            if ($find) {
                (Get-Content -Path $filePath) -replace $find, $replace | Add-Content $tempFilePath
            } else {
                $replace = "winkernel:`r`n  networkName:" + $networkName + "`r`n"
                $find = get-content $filePath | ForEach-Object -Process {if($_.Contains("winkernel:")) {$_}}
                if ($find) {
                    (Get-Content -Path $filePath) -replace $find, $replace | Add-Content $tempFilePath    
                } else {
                    (Get-Content -Path $filePath) + $replace | Add-Content $tempFilePath
                }    
            }
            Remove-Item -Path $filePath
            Move-Item -Path $tempFilePath -Destination $filePath

            $find = get-content $filePath | ForEach-Object -Process {if($_.Contains("WinOverlay:")) {$_}}
            $replace = "  WinOverlay: " + "true"
            if ($find) {
                (Get-Content -Path $filePath) -replace $find, $replace | Add-Content $tempFilePath
            } else {
                $replace = "featureGates:`r`n  WinOverlay: true`r`n"
                $find = get-content $filePath | ForEach-Object -Process {if($_.Contains("featureGates:")) {$_}}
                if ($find) {
                    (Get-Content -Path $filePath) -replace $find, $replace | Add-Content $tempFilePath    
                } else {
                    (Get-Content -Path $filePath) + $replace | Add-Content $tempFilePath
                }    
            }
            Remove-Item -Path $filePath
            Move-Item -Path $tempFilePath -Destination $filePath
            
            $find = get-content $filePath | ForEach-Object -Process {if($_.Contains("mode:")) {$_}}
            $replace = "mode: " + "kernelspace"
            if ($find) {
                (Get-Content -Path $filePath) -replace $find, $replace | Add-Content $tempFilePath
            } else {
                $replace = "mode: kernelspace`r`n"
                (Get-Content -Path $filePath) + $replace | Add-Content $tempFilePath
            }
            Remove-Item -Path $filePath
            Move-Item -Path $tempFilePath -Destination $filePath
            wins cli process run --path /kube-proxy/kube-proxy.exe --args "--v=6 --config=/var/lib/kube-proxy/config.conf --hostname-override=$env:NODE_NAME --feature-gates=WinOverlay=true"
        kind: ConfigMap
        apiVersion: v1
        metadata:
          labels:
            app: kube-proxy 
          name: kube-proxy-windows
          namespace: kube-system
        ---
        apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          labels:
            k8s-app: kube-proxy
          name: kube-proxy-windows
          namespace: kube-system
        spec:
          selector:
            matchLabels:
              k8s-app: kube-proxy-windows
          template:
            metadata:
              labels:
                k8s-app: kube-proxy-windows
            spec:
              serviceAccountName: kube-proxy
              containers:
              - command:
                - powershell
                args:
                - -file
                - /var/lib/kube-proxy-windows/run-script.ps1
                env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                image: kubeproxywin/kube-proxy
                imagePullPolicy: IfNotPresent
                name: kube-proxy
                volumeMounts:
                - name: host
                  mountPath: /host
                - name: wins
                  mountPath: \\.\pipe\rancher_wins
                - mountPath: /var/lib/kube-proxy
                  name: kube-proxy
                - mountPath: /var/lib/kube-proxy-windows
                  name: kube-proxy-windows
              nodeSelector:
                beta.kubernetes.io/os: windows
              tolerations:
              - key: CriticalAddonsOnly
                operator: Exists
              - operator: Exists
              volumes:
              - configMap:
                  defaultMode: 420
                  name: kube-proxy-windows
                name: kube-proxy-windows
              - configMap:
                  name: kube-proxy
                name: kube-proxy
              - hostPath:
                  path: /
                name: host
              - name: wins
                hostPath:
                  path: \\.\pipe\rancher_wins
                  type: null
          updateStrategy:
            type: RollingUpdate
    - path: /tmp/kubeadm-bootstrap.sh
      owner: "root:root"
      permissions: "0744"
      content: |
        #!/bin/bash
  
        set -eux
  
        function os_setup {
          command -v "awk" >/dev/null 2>&1 || tdnf install -y awk
        }
  
        function dockerd_prereq() {
          swapoff -a
          modprobe overlay
          modprobe br_netfilter
  
          cat > /etc/sysctl.d/99-sysctl-kubernetes-cri.conf <<EOF
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF
  
          iptables -P INPUT ACCEPT
          iptables -P OUTPUT ACCEPT
          iptables -P FORWARD ACCEPT
  
          sysctl --system
        }
  
        function systemctl_config() {
          systemctl daemon-reload
          systemctl enable docker
          systemctl restart docker
          systemctl enable azurestackhci_boot
        }
  
        function kubernetes_install() {
          K8S_VERSION="${KUBERNETES_VERSION}"
          KUBEADM_VERSION="${KUBERNETES_VERSION}"
          # tdnf install -y kubernetes-${KUBERNETES_VERSION} kubernetes-kubeadm-${KUBERNETES_VERSION} kubernetes-pause-${KUBERNETES_VERSION}
  
          cat > /etc/sysctl.d/90-kubelet.conf << EOF
        vm.overcommit_memory=1
        kernel.panic=10
        kernel.panic_on_oops=1
        EOF
          sysctl -p /etc/sysctl.d/90-kubelet.conf
          sudo swapoff -a
        }
  
        os_setup
        dockerd_prereq
        systemctl_config
        kubernetes_install
    - path: /tmp/kubeadm-postinstall.sh
      owner: "root:root"
      permissions: "0744"
      content: |
        #!/bin/bash
  
        set -euxo pipefail

        function flannel_install() {
          KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f /etc/kubernetes/cni/kube-flannel.yml
        }

        function kube_proxy_install() {
          KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f /etc/kubernetes/cni/win-kube-proxy.yaml
        }
  
        # Temp, this responsibility will move to caph
        function patch_node_providerid() {
          for value in {1..10}
          do
            sleep 1
            echo "Patch ProviderID (attempt $value)..."
            KUBECONFIG=/etc/kubernetes/admin.conf kubectl patch node {{ ds.meta_data["local_hostname"] }} -p $'spec:\n providerID: azurestackhci:////{{ ds.meta_data["local_hostname"] }}' >/dev/null 2>&1 || continue
            break
          done
        }
  
        function save_iptables_config() {
          iptables-save > /etc/sysconfig/iptables
        }
  
        flannel_install
        kube_proxy_install
        save_iptables_config
        patch_node_providerid
  version: "${KUBERNETES_VERSION}"
---
kind: AzureStackHCIMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      location: "westus"
      vmSize: ${AZURESTACKHCI_CONTROL_PLANE_MACHINE_TYPE}
      sshPublicKey: ${AZURESTACKHCI_SSH_PUBLIC_KEY}
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-md-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: "${CLUSTER_NAME}-md-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureStackHCIMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureStackHCIMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      location: "westus"
      vmSize: ${AZURESTACKHCI_NODE_MACHINE_TYPE}
      sshPublicKey: ${AZURESTACKHCI_SSH_PUBLIC_KEY}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data["local_hostname"] }}'
      preKubeadmCommands:
        - bash -c /tmp/kubeadm-bootstrap.sh
      postKubeadmCommands:
        - bash -c /tmp/kubeadm-postinstall.sh
      files:
        - path: /etc/rc.d/init.d/azurestackhci_boot.sh
          owner: root:root
          permissions: '0755'
          content: |
            #!/bin/bash
            iptables-restore -v -w < /etc/sysconfig/iptables
        - path: /etc/systemd/system/azurestackhci_boot.service
          owner: root:root
          permissions: '0644'
          content: |
            [Unit]
            Description=azurestackhci_boot
            After=network.target
            
            [Service]
            Type=simple
            ExecStart=/etc/rc.d/init.d/azurestackhci_boot.sh
            TimeoutStartSec=0
            
            [Install]
            WantedBy=default.target
        - path: /tmp/kubeadm-postinstall.sh
          owner: "root:root"
          permissions: "0744"
          content: |
            #!/bin/bash

            set -euxo pipefail

            # Temp, this responsibility will move to caph
            function patch_node_providerid() {
              for value in {1..10}
              do
                sleep 1
                echo "Patch ProviderID (attempt $value)..."
                KUBECONFIG=/etc/kubernetes/kubelet.conf kubectl patch node {{ ds.meta_data["local_hostname"] }} -p $'spec:\n providerID: azurestackhci:////{{ ds.meta_data["local_hostname"] }}' >/dev/null 2>&1 || continue
                break
              done
            }

            function save_iptables_config() {
              iptables-save > /etc/sysconfig/iptables
            }

            save_iptables_config
            patch_node_providerid
        - path: /tmp/kubeadm-bootstrap.sh
          owner: "root:root"
          permissions: "0744"
          content: |
            #!/bin/bash

            set -eux

            function os_setup {
              command -v "awk" >/dev/null 2>&1 || tdnf install -y awk
            }

            function dockerd_prereq() {
              swapoff -a
              modprobe overlay
              modprobe br_netfilter

              cat > /etc/sysctl.d/99-sysctl-kubernetes-cri.conf <<EOF
            net.bridge.bridge-nf-call-iptables  = 1
            net.ipv4.ip_forward                 = 1
            net.bridge.bridge-nf-call-ip6tables = 1
            EOF

              iptables -P INPUT ACCEPT
              iptables -P OUTPUT ACCEPT
              iptables -P FORWARD ACCEPT

              sysctl --system
            }

            function systemctl_config() {
              systemctl daemon-reload
              systemctl enable docker
              systemctl restart docker
              systemctl enable azurestackhci_boot
            }

            function kubernetes_install() {
              K8S_VERSION="${KUBERNETES_VERSION}"
              KUBEADM_VERSION="${KUBERNETES_VERSION}"
              # tdnf install -y kubernetes-${KUBERNETES_VERSION} kubernetes-kubeadm-${KUBERNETES_VERSION} kubernetes-pause-${KUBERNETES_VERSION}

              cat > /etc/sysctl.d/90-kubelet.conf << EOF
            vm.overcommit_memory=1
            kernel.panic=10
            kernel.panic_on_oops=1
            EOF
              sysctl -p /etc/sysctl.d/90-kubelet.conf
              sudo swapoff -a
            }

            os_setup
            dockerd_prereq
            systemctl_config
            kubernetes_install
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-md-1"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${AZURESTACKHCI_WINDOWS_WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "1.16.2"
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-md-1"
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: "${CLUSTER_NAME}-md-1"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureStackHCIMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureStackHCIMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-1"
spec:
  template:
    spec:  
      image:
        name: "windows_k8s"
        publisher: "na"
        offer: "windows"
        sku: "windows"
        version: "latest"
      osDisk:
        name: "na"
        diskSizeGB: 30
        osType: "Windows"
        managedDisk:
          storageAccountType: "na"
        source: "na"
      location: "westus"
      vmSize: ${AZURESTACKHCI_NODE_MACHINE_TYPE}
      sshPublicKey: ${AZURESTACKHCI_SSH_PUBLIC_KEY}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-1"
spec:
  template:
    spec:
      files:
        - path: C:\ECP-Cache\WaitForDocker.ps1
          permissions: "0744"
          content: |
            #ps1
            for($i = 0; $i -lt 60; $i++) {
              if ((Get-Service docker).Status -eq "Running")
              {
                echo "Docker service is running."
                exit
              }
              echo "Waiting docker service..."
              start-sleep -s 2
            }
        - path: C:\ECP-Cache\ApplyPatch.ps1
          permissions: "0744"
          content: |
            #ps1
            C:\ECP-Cache\kubernetes\kubectl.exe --kubeconfig=C:\etc\kubernetes\kubelet.conf patch node {{ v1.local_hostname }} -p "spec:`r`n providerID: azurestackhci:////{{ v1.local_hostname }}"
      joinConfiguration:
        nodeRegistration:
          name: '{{ v1.local_hostname }}'
      preKubeadmCommands:
        - powershell C:\ECP-Cache\WaitForDocker.ps1
        - docker network create -d nat host
        - powershell -C "ipmo C:\ECP-Cache\hns.psm1;New-HNSNetwork -Type \"overlay\" -AddressPrefix \"192.168.255.0/30\" -Gateway \"192.168.255.1\" -Name \"External\" -AdapterName \"Ethernet 2\" -SubnetPolicies @(@{Type = \"VSID\"; VSID = 9999; }); start-sleep 10;"  
      postKubeadmCommands:
        - powershell C:\ECP-Cache\StartFlannel.ps1
        - copy C:\Users\Administrator\.ssh\authorized_keys C:\ProgramData\ssh\administrators_authorized_keys
        - icacls C:\ProgramData\ssh\administrators_authorized_keys /inheritance:r
        - icacls C:\ProgramData\ssh\administrators_authorized_keys /grant "NT AUTHORITY\SYSTEM":R
        - powershell C:\ECP-Cache\ApplyPatch.ps1
