// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.
Portions Copyright © Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen-v0.20.2. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1alpha4 "github.com/microsoft/cluster-api-provider-azurestackhci/api/v1alpha4"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AvailabilityZone)(nil), (*v1alpha4.AvailabilityZone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AvailabilityZone_To_v1alpha4_AvailabilityZone(a.(*AvailabilityZone), b.(*v1alpha4.AvailabilityZone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AvailabilityZone)(nil), (*AvailabilityZone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AvailabilityZone_To_v1alpha3_AvailabilityZone(a.(*v1alpha4.AvailabilityZone), b.(*AvailabilityZone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCICluster)(nil), (*v1alpha4.AzureStackHCICluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(a.(*AzureStackHCICluster), b.(*v1alpha4.AzureStackHCICluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCICluster)(nil), (*AzureStackHCICluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCICluster_To_v1alpha3_AzureStackHCICluster(a.(*v1alpha4.AzureStackHCICluster), b.(*AzureStackHCICluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterList)(nil), (*v1alpha4.AzureStackHCIClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList(a.(*AzureStackHCIClusterList), b.(*v1alpha4.AzureStackHCIClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIClusterList)(nil), (*AzureStackHCIClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIClusterList_To_v1alpha3_AzureStackHCIClusterList(a.(*v1alpha4.AzureStackHCIClusterList), b.(*AzureStackHCIClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterSpec)(nil), (*v1alpha4.AzureStackHCIClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(a.(*AzureStackHCIClusterSpec), b.(*v1alpha4.AzureStackHCIClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIClusterSpec)(nil), (*AzureStackHCIClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIClusterSpec_To_v1alpha3_AzureStackHCIClusterSpec(a.(*v1alpha4.AzureStackHCIClusterSpec), b.(*AzureStackHCIClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIClusterStatus)(nil), (*v1alpha4.AzureStackHCIClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(a.(*AzureStackHCIClusterStatus), b.(*v1alpha4.AzureStackHCIClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIClusterStatus)(nil), (*AzureStackHCIClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIClusterStatus_To_v1alpha3_AzureStackHCIClusterStatus(a.(*v1alpha4.AzureStackHCIClusterStatus), b.(*AzureStackHCIClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancer)(nil), (*v1alpha4.AzureStackHCILoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer(a.(*AzureStackHCILoadBalancer), b.(*v1alpha4.AzureStackHCILoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCILoadBalancer)(nil), (*AzureStackHCILoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCILoadBalancer_To_v1alpha3_AzureStackHCILoadBalancer(a.(*v1alpha4.AzureStackHCILoadBalancer), b.(*AzureStackHCILoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancerList)(nil), (*v1alpha4.AzureStackHCILoadBalancerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList(a.(*AzureStackHCILoadBalancerList), b.(*v1alpha4.AzureStackHCILoadBalancerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCILoadBalancerList)(nil), (*AzureStackHCILoadBalancerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCILoadBalancerList_To_v1alpha3_AzureStackHCILoadBalancerList(a.(*v1alpha4.AzureStackHCILoadBalancerList), b.(*AzureStackHCILoadBalancerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancerSpec)(nil), (*v1alpha4.AzureStackHCILoadBalancerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(a.(*AzureStackHCILoadBalancerSpec), b.(*v1alpha4.AzureStackHCILoadBalancerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCILoadBalancerSpec)(nil), (*AzureStackHCILoadBalancerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1alpha3_AzureStackHCILoadBalancerSpec(a.(*v1alpha4.AzureStackHCILoadBalancerSpec), b.(*AzureStackHCILoadBalancerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCILoadBalancerStatus)(nil), (*v1alpha4.AzureStackHCILoadBalancerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(a.(*AzureStackHCILoadBalancerStatus), b.(*v1alpha4.AzureStackHCILoadBalancerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCILoadBalancerStatus)(nil), (*AzureStackHCILoadBalancerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1alpha3_AzureStackHCILoadBalancerStatus(a.(*v1alpha4.AzureStackHCILoadBalancerStatus), b.(*AzureStackHCILoadBalancerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachine)(nil), (*v1alpha4.AzureStackHCIMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine(a.(*AzureStackHCIMachine), b.(*v1alpha4.AzureStackHCIMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachine)(nil), (*AzureStackHCIMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachine_To_v1alpha3_AzureStackHCIMachine(a.(*v1alpha4.AzureStackHCIMachine), b.(*AzureStackHCIMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineList)(nil), (*v1alpha4.AzureStackHCIMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList(a.(*AzureStackHCIMachineList), b.(*v1alpha4.AzureStackHCIMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachineList)(nil), (*AzureStackHCIMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineList_To_v1alpha3_AzureStackHCIMachineList(a.(*v1alpha4.AzureStackHCIMachineList), b.(*AzureStackHCIMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineProviderCondition)(nil), (*v1alpha4.AzureStackHCIMachineProviderCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition(a.(*AzureStackHCIMachineProviderCondition), b.(*v1alpha4.AzureStackHCIMachineProviderCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachineProviderCondition)(nil), (*AzureStackHCIMachineProviderCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1alpha3_AzureStackHCIMachineProviderCondition(a.(*v1alpha4.AzureStackHCIMachineProviderCondition), b.(*AzureStackHCIMachineProviderCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineSpec)(nil), (*v1alpha4.AzureStackHCIMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(a.(*AzureStackHCIMachineSpec), b.(*v1alpha4.AzureStackHCIMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachineSpec)(nil), (*AzureStackHCIMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1alpha3_AzureStackHCIMachineSpec(a.(*v1alpha4.AzureStackHCIMachineSpec), b.(*AzureStackHCIMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineStatus)(nil), (*v1alpha4.AzureStackHCIMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(a.(*AzureStackHCIMachineStatus), b.(*v1alpha4.AzureStackHCIMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachineStatus)(nil), (*AzureStackHCIMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineStatus_To_v1alpha3_AzureStackHCIMachineStatus(a.(*v1alpha4.AzureStackHCIMachineStatus), b.(*AzureStackHCIMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplate)(nil), (*v1alpha4.AzureStackHCIMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate(a.(*AzureStackHCIMachineTemplate), b.(*v1alpha4.AzureStackHCIMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachineTemplate)(nil), (*AzureStackHCIMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineTemplate_To_v1alpha3_AzureStackHCIMachineTemplate(a.(*v1alpha4.AzureStackHCIMachineTemplate), b.(*AzureStackHCIMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateList)(nil), (*v1alpha4.AzureStackHCIMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList(a.(*AzureStackHCIMachineTemplateList), b.(*v1alpha4.AzureStackHCIMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachineTemplateList)(nil), (*AzureStackHCIMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1alpha3_AzureStackHCIMachineTemplateList(a.(*v1alpha4.AzureStackHCIMachineTemplateList), b.(*AzureStackHCIMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateResource)(nil), (*v1alpha4.AzureStackHCIMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(a.(*AzureStackHCIMachineTemplateResource), b.(*v1alpha4.AzureStackHCIMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachineTemplateResource)(nil), (*AzureStackHCIMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1alpha3_AzureStackHCIMachineTemplateResource(a.(*v1alpha4.AzureStackHCIMachineTemplateResource), b.(*AzureStackHCIMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIMachineTemplateSpec)(nil), (*v1alpha4.AzureStackHCIMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(a.(*AzureStackHCIMachineTemplateSpec), b.(*v1alpha4.AzureStackHCIMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIMachineTemplateSpec)(nil), (*AzureStackHCIMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1alpha3_AzureStackHCIMachineTemplateSpec(a.(*v1alpha4.AzureStackHCIMachineTemplateSpec), b.(*AzureStackHCIMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIResourceReference)(nil), (*v1alpha4.AzureStackHCIResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference(a.(*AzureStackHCIResourceReference), b.(*v1alpha4.AzureStackHCIResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIResourceReference)(nil), (*AzureStackHCIResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIResourceReference_To_v1alpha3_AzureStackHCIResourceReference(a.(*v1alpha4.AzureStackHCIResourceReference), b.(*AzureStackHCIResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachine)(nil), (*v1alpha4.AzureStackHCIVirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine(a.(*AzureStackHCIVirtualMachine), b.(*v1alpha4.AzureStackHCIVirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIVirtualMachine)(nil), (*AzureStackHCIVirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIVirtualMachine_To_v1alpha3_AzureStackHCIVirtualMachine(a.(*v1alpha4.AzureStackHCIVirtualMachine), b.(*AzureStackHCIVirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachineList)(nil), (*v1alpha4.AzureStackHCIVirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList(a.(*AzureStackHCIVirtualMachineList), b.(*v1alpha4.AzureStackHCIVirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIVirtualMachineList)(nil), (*AzureStackHCIVirtualMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1alpha3_AzureStackHCIVirtualMachineList(a.(*v1alpha4.AzureStackHCIVirtualMachineList), b.(*AzureStackHCIVirtualMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachineSpec)(nil), (*v1alpha4.AzureStackHCIVirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(a.(*AzureStackHCIVirtualMachineSpec), b.(*v1alpha4.AzureStackHCIVirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIVirtualMachineSpec)(nil), (*AzureStackHCIVirtualMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1alpha3_AzureStackHCIVirtualMachineSpec(a.(*v1alpha4.AzureStackHCIVirtualMachineSpec), b.(*AzureStackHCIVirtualMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureStackHCIVirtualMachineStatus)(nil), (*v1alpha4.AzureStackHCIVirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(a.(*AzureStackHCIVirtualMachineStatus), b.(*v1alpha4.AzureStackHCIVirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AzureStackHCIVirtualMachineStatus)(nil), (*AzureStackHCIVirtualMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1alpha3_AzureStackHCIVirtualMachineStatus(a.(*v1alpha4.AzureStackHCIVirtualMachineStatus), b.(*AzureStackHCIVirtualMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Image)(nil), (*v1alpha4.Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Image_To_v1alpha4_Image(a.(*Image), b.(*v1alpha4.Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Image)(nil), (*Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Image_To_v1alpha3_Image(a.(*v1alpha4.Image), b.(*Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedDisk)(nil), (*v1alpha4.ManagedDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ManagedDisk_To_v1alpha4_ManagedDisk(a.(*ManagedDisk), b.(*v1alpha4.ManagedDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.ManagedDisk)(nil), (*ManagedDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ManagedDisk_To_v1alpha3_ManagedDisk(a.(*v1alpha4.ManagedDisk), b.(*ManagedDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSpec)(nil), (*v1alpha4.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec(a.(*NetworkSpec), b.(*v1alpha4.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec(a.(*v1alpha4.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OSDisk)(nil), (*v1alpha4.OSDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_OSDisk_To_v1alpha4_OSDisk(a.(*OSDisk), b.(*v1alpha4.OSDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OSDisk)(nil), (*OSDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OSDisk_To_v1alpha3_OSDisk(a.(*v1alpha4.OSDisk), b.(*OSDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetSpec)(nil), (*v1alpha4.SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec(a.(*SubnetSpec), b.(*v1alpha4.SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.SubnetSpec)(nil), (*SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec(a.(*v1alpha4.SubnetSpec), b.(*SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VM)(nil), (*v1alpha4.VM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VM_To_v1alpha4_VM(a.(*VM), b.(*v1alpha4.VM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.VM)(nil), (*VM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_VM_To_v1alpha3_VM(a.(*v1alpha4.VM), b.(*VM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VnetSpec)(nil), (*v1alpha4.VnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VnetSpec_To_v1alpha4_VnetSpec(a.(*VnetSpec), b.(*v1alpha4.VnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.VnetSpec)(nil), (*VnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_VnetSpec_To_v1alpha3_VnetSpec(a.(*v1alpha4.VnetSpec), b.(*VnetSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_AvailabilityZone_To_v1alpha4_AvailabilityZone(in *AvailabilityZone, out *v1alpha4.AvailabilityZone, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha3_AvailabilityZone_To_v1alpha4_AvailabilityZone is an autogenerated conversion function.
func Convert_v1alpha3_AvailabilityZone_To_v1alpha4_AvailabilityZone(in *AvailabilityZone, out *v1alpha4.AvailabilityZone, s conversion.Scope) error {
	return autoConvert_v1alpha3_AvailabilityZone_To_v1alpha4_AvailabilityZone(in, out, s)
}

func autoConvert_v1alpha4_AvailabilityZone_To_v1alpha3_AvailabilityZone(in *v1alpha4.AvailabilityZone, out *AvailabilityZone, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha4_AvailabilityZone_To_v1alpha3_AvailabilityZone is an autogenerated conversion function.
func Convert_v1alpha4_AvailabilityZone_To_v1alpha3_AvailabilityZone(in *v1alpha4.AvailabilityZone, out *AvailabilityZone, s conversion.Scope) error {
	return autoConvert_v1alpha4_AvailabilityZone_To_v1alpha3_AvailabilityZone(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(in *AzureStackHCICluster, out *v1alpha4.AzureStackHCICluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(in *AzureStackHCICluster, out *v1alpha4.AzureStackHCICluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCICluster_To_v1alpha4_AzureStackHCICluster(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCICluster_To_v1alpha3_AzureStackHCICluster(in *v1alpha4.AzureStackHCICluster, out *AzureStackHCICluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCIClusterSpec_To_v1alpha3_AzureStackHCIClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AzureStackHCIClusterStatus_To_v1alpha3_AzureStackHCIClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCICluster_To_v1alpha3_AzureStackHCICluster is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCICluster_To_v1alpha3_AzureStackHCICluster(in *v1alpha4.AzureStackHCICluster, out *AzureStackHCICluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCICluster_To_v1alpha3_AzureStackHCICluster(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList(in *AzureStackHCIClusterList, out *v1alpha4.AzureStackHCIClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.AzureStackHCICluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList(in *AzureStackHCIClusterList, out *v1alpha4.AzureStackHCIClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIClusterList_To_v1alpha4_AzureStackHCIClusterList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIClusterList_To_v1alpha3_AzureStackHCIClusterList(in *v1alpha4.AzureStackHCIClusterList, out *AzureStackHCIClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCICluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCIClusterList_To_v1alpha3_AzureStackHCIClusterList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIClusterList_To_v1alpha3_AzureStackHCIClusterList(in *v1alpha4.AzureStackHCIClusterList, out *AzureStackHCIClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIClusterList_To_v1alpha3_AzureStackHCIClusterList(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(in *AzureStackHCIClusterSpec, out *v1alpha4.AzureStackHCIClusterSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec(&in.NetworkSpec, &out.NetworkSpec, s); err != nil {
		return err
	}
	out.ResourceGroup = in.ResourceGroup
	out.Location = in.Location
	out.AzureStackHCILoadBalancer = (*v1alpha4.AzureStackHCILoadBalancerSpec)(unsafe.Pointer(in.AzureStackHCILoadBalancer))
	out.ControlPlaneEndpoint = apiv1alpha4.APIEndpoint(in.ControlPlaneEndpoint)
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.Management = in.Management
	return nil
}

// Convert_v1alpha3_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(in *AzureStackHCIClusterSpec, out *v1alpha4.AzureStackHCIClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIClusterSpec_To_v1alpha4_AzureStackHCIClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIClusterSpec_To_v1alpha3_AzureStackHCIClusterSpec(in *v1alpha4.AzureStackHCIClusterSpec, out *AzureStackHCIClusterSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec(&in.NetworkSpec, &out.NetworkSpec, s); err != nil {
		return err
	}
	out.ResourceGroup = in.ResourceGroup
	out.Location = in.Location
	out.AzureStackHCILoadBalancer = (*AzureStackHCILoadBalancerSpec)(unsafe.Pointer(in.AzureStackHCILoadBalancer))
	out.ControlPlaneEndpoint = apiv1alpha3.APIEndpoint(in.ControlPlaneEndpoint)
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.Management = in.Management
	return nil
}

// Convert_v1alpha4_AzureStackHCIClusterSpec_To_v1alpha3_AzureStackHCIClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIClusterSpec_To_v1alpha3_AzureStackHCIClusterSpec(in *v1alpha4.AzureStackHCIClusterSpec, out *AzureStackHCIClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIClusterSpec_To_v1alpha3_AzureStackHCIClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(in *AzureStackHCIClusterStatus, out *v1alpha4.AzureStackHCIClusterStatus, s conversion.Scope) error {
	if err := Convert_v1alpha3_VM_To_v1alpha4_VM(&in.Bastion, &out.Bastion, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	out.Phase = in.Phase
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha3_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(in *AzureStackHCIClusterStatus, out *v1alpha4.AzureStackHCIClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIClusterStatus_To_v1alpha4_AzureStackHCIClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIClusterStatus_To_v1alpha3_AzureStackHCIClusterStatus(in *v1alpha4.AzureStackHCIClusterStatus, out *AzureStackHCIClusterStatus, s conversion.Scope) error {
	if err := Convert_v1alpha4_VM_To_v1alpha3_VM(&in.Bastion, &out.Bastion, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	out.Phase = in.Phase
	out.Conditions = *(*apiv1alpha3.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha4_AzureStackHCIClusterStatus_To_v1alpha3_AzureStackHCIClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIClusterStatus_To_v1alpha3_AzureStackHCIClusterStatus(in *v1alpha4.AzureStackHCIClusterStatus, out *AzureStackHCIClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIClusterStatus_To_v1alpha3_AzureStackHCIClusterStatus(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer(in *AzureStackHCILoadBalancer, out *v1alpha4.AzureStackHCILoadBalancer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer(in *AzureStackHCILoadBalancer, out *v1alpha4.AzureStackHCILoadBalancer, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCILoadBalancer_To_v1alpha4_AzureStackHCILoadBalancer(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCILoadBalancer_To_v1alpha3_AzureStackHCILoadBalancer(in *v1alpha4.AzureStackHCILoadBalancer, out *AzureStackHCILoadBalancer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1alpha3_AzureStackHCILoadBalancerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1alpha3_AzureStackHCILoadBalancerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCILoadBalancer_To_v1alpha3_AzureStackHCILoadBalancer is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCILoadBalancer_To_v1alpha3_AzureStackHCILoadBalancer(in *v1alpha4.AzureStackHCILoadBalancer, out *AzureStackHCILoadBalancer, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCILoadBalancer_To_v1alpha3_AzureStackHCILoadBalancer(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList(in *AzureStackHCILoadBalancerList, out *v1alpha4.AzureStackHCILoadBalancerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.AzureStackHCILoadBalancer)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList(in *AzureStackHCILoadBalancerList, out *v1alpha4.AzureStackHCILoadBalancerList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCILoadBalancerList_To_v1alpha4_AzureStackHCILoadBalancerList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCILoadBalancerList_To_v1alpha3_AzureStackHCILoadBalancerList(in *v1alpha4.AzureStackHCILoadBalancerList, out *AzureStackHCILoadBalancerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCILoadBalancer)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCILoadBalancerList_To_v1alpha3_AzureStackHCILoadBalancerList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCILoadBalancerList_To_v1alpha3_AzureStackHCILoadBalancerList(in *v1alpha4.AzureStackHCILoadBalancerList, out *AzureStackHCILoadBalancerList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCILoadBalancerList_To_v1alpha3_AzureStackHCILoadBalancerList(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(in *AzureStackHCILoadBalancerSpec, out *v1alpha4.AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	out.SSHPublicKey = in.SSHPublicKey
	if err := Convert_v1alpha3_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.VMSize = in.VMSize
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

// Convert_v1alpha3_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(in *AzureStackHCILoadBalancerSpec, out *v1alpha4.AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCILoadBalancerSpec_To_v1alpha4_AzureStackHCILoadBalancerSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1alpha3_AzureStackHCILoadBalancerSpec(in *v1alpha4.AzureStackHCILoadBalancerSpec, out *AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	out.SSHPublicKey = in.SSHPublicKey
	if err := Convert_v1alpha4_Image_To_v1alpha3_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.VMSize = in.VMSize
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

// Convert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1alpha3_AzureStackHCILoadBalancerSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1alpha3_AzureStackHCILoadBalancerSpec(in *v1alpha4.AzureStackHCILoadBalancerSpec, out *AzureStackHCILoadBalancerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCILoadBalancerSpec_To_v1alpha3_AzureStackHCILoadBalancerSpec(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(in *AzureStackHCILoadBalancerStatus, out *v1alpha4.AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.ReadyReplicas = in.ReadyReplicas
	out.FailedReplicas = in.FailedReplicas
	out.Address = in.Address
	out.Port = in.Port
	out.Phase = in.Phase
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ErrorReason = (*errors.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.Selector = in.Selector
	return nil
}

// Convert_v1alpha3_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(in *AzureStackHCILoadBalancerStatus, out *v1alpha4.AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCILoadBalancerStatus_To_v1alpha4_AzureStackHCILoadBalancerStatus(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1alpha3_AzureStackHCILoadBalancerStatus(in *v1alpha4.AzureStackHCILoadBalancerStatus, out *AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.ReadyReplicas = in.ReadyReplicas
	out.FailedReplicas = in.FailedReplicas
	out.Address = in.Address
	out.Port = in.Port
	out.Phase = in.Phase
	out.Conditions = *(*apiv1alpha3.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ErrorReason = (*errors.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.Selector = in.Selector
	return nil
}

// Convert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1alpha3_AzureStackHCILoadBalancerStatus is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1alpha3_AzureStackHCILoadBalancerStatus(in *v1alpha4.AzureStackHCILoadBalancerStatus, out *AzureStackHCILoadBalancerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCILoadBalancerStatus_To_v1alpha3_AzureStackHCILoadBalancerStatus(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine(in *AzureStackHCIMachine, out *v1alpha4.AzureStackHCIMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine(in *AzureStackHCIMachine, out *v1alpha4.AzureStackHCIMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachine_To_v1alpha4_AzureStackHCIMachine(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachine_To_v1alpha3_AzureStackHCIMachine(in *v1alpha4.AzureStackHCIMachine, out *AzureStackHCIMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1alpha3_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AzureStackHCIMachineStatus_To_v1alpha3_AzureStackHCIMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachine_To_v1alpha3_AzureStackHCIMachine is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachine_To_v1alpha3_AzureStackHCIMachine(in *v1alpha4.AzureStackHCIMachine, out *AzureStackHCIMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachine_To_v1alpha3_AzureStackHCIMachine(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList(in *AzureStackHCIMachineList, out *v1alpha4.AzureStackHCIMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.AzureStackHCIMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList(in *AzureStackHCIMachineList, out *v1alpha4.AzureStackHCIMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachineList_To_v1alpha4_AzureStackHCIMachineList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineList_To_v1alpha3_AzureStackHCIMachineList(in *v1alpha4.AzureStackHCIMachineList, out *AzureStackHCIMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCIMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineList_To_v1alpha3_AzureStackHCIMachineList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineList_To_v1alpha3_AzureStackHCIMachineList(in *v1alpha4.AzureStackHCIMachineList, out *AzureStackHCIMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineList_To_v1alpha3_AzureStackHCIMachineList(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition(in *AzureStackHCIMachineProviderCondition, out *v1alpha4.AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	out.Type = v1alpha4.AzureStackHCIMachineProviderConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition(in *AzureStackHCIMachineProviderCondition, out *v1alpha4.AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachineProviderCondition_To_v1alpha4_AzureStackHCIMachineProviderCondition(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1alpha3_AzureStackHCIMachineProviderCondition(in *v1alpha4.AzureStackHCIMachineProviderCondition, out *AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	out.Type = AzureStackHCIMachineProviderConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1alpha3_AzureStackHCIMachineProviderCondition is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1alpha3_AzureStackHCIMachineProviderCondition(in *v1alpha4.AzureStackHCIMachineProviderCondition, out *AzureStackHCIMachineProviderCondition, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineProviderCondition_To_v1alpha3_AzureStackHCIMachineProviderCondition(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(in *AzureStackHCIMachineSpec, out *v1alpha4.AzureStackHCIMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VMSize = in.VMSize
	if err := Convert_v1alpha3_AvailabilityZone_To_v1alpha4_AvailabilityZone(&in.AvailabilityZone, &out.AvailabilityZone, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_OSDisk_To_v1alpha4_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.AllocatePublicIP = in.AllocatePublicIP
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(in *AzureStackHCIMachineSpec, out *v1alpha4.AzureStackHCIMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineSpec_To_v1alpha3_AzureStackHCIMachineSpec(in *v1alpha4.AzureStackHCIMachineSpec, out *AzureStackHCIMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VMSize = in.VMSize
	if err := Convert_v1alpha4_AvailabilityZone_To_v1alpha3_AvailabilityZone(&in.AvailabilityZone, &out.AvailabilityZone, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_Image_To_v1alpha3_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_OSDisk_To_v1alpha3_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.AllocatePublicIP = in.AllocatePublicIP
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1alpha3_AzureStackHCIMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1alpha3_AzureStackHCIMachineSpec(in *v1alpha4.AzureStackHCIMachineSpec, out *AzureStackHCIMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineSpec_To_v1alpha3_AzureStackHCIMachineSpec(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(in *AzureStackHCIMachineStatus, out *v1alpha4.AzureStackHCIMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*v1alpha4.VMState)(unsafe.Pointer(in.VMState))
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(in *AzureStackHCIMachineStatus, out *v1alpha4.AzureStackHCIMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachineStatus_To_v1alpha4_AzureStackHCIMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineStatus_To_v1alpha3_AzureStackHCIMachineStatus(in *v1alpha4.AzureStackHCIMachineStatus, out *AzureStackHCIMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*VMState)(unsafe.Pointer(in.VMState))
	out.Conditions = *(*apiv1alpha3.Conditions)(unsafe.Pointer(&in.Conditions))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineStatus_To_v1alpha3_AzureStackHCIMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineStatus_To_v1alpha3_AzureStackHCIMachineStatus(in *v1alpha4.AzureStackHCIMachineStatus, out *AzureStackHCIMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineStatus_To_v1alpha3_AzureStackHCIMachineStatus(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate(in *AzureStackHCIMachineTemplate, out *v1alpha4.AzureStackHCIMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate(in *AzureStackHCIMachineTemplate, out *v1alpha4.AzureStackHCIMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachineTemplate_To_v1alpha4_AzureStackHCIMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineTemplate_To_v1alpha3_AzureStackHCIMachineTemplate(in *v1alpha4.AzureStackHCIMachineTemplate, out *AzureStackHCIMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1alpha3_AzureStackHCIMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineTemplate_To_v1alpha3_AzureStackHCIMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineTemplate_To_v1alpha3_AzureStackHCIMachineTemplate(in *v1alpha4.AzureStackHCIMachineTemplate, out *AzureStackHCIMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineTemplate_To_v1alpha3_AzureStackHCIMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList(in *AzureStackHCIMachineTemplateList, out *v1alpha4.AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.AzureStackHCIMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList(in *AzureStackHCIMachineTemplateList, out *v1alpha4.AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachineTemplateList_To_v1alpha4_AzureStackHCIMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1alpha3_AzureStackHCIMachineTemplateList(in *v1alpha4.AzureStackHCIMachineTemplateList, out *AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCIMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1alpha3_AzureStackHCIMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1alpha3_AzureStackHCIMachineTemplateList(in *v1alpha4.AzureStackHCIMachineTemplateList, out *AzureStackHCIMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineTemplateList_To_v1alpha3_AzureStackHCIMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(in *AzureStackHCIMachineTemplateResource, out *v1alpha4.AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_AzureStackHCIMachineSpec_To_v1alpha4_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(in *AzureStackHCIMachineTemplateResource, out *v1alpha4.AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1alpha3_AzureStackHCIMachineTemplateResource(in *v1alpha4.AzureStackHCIMachineTemplateResource, out *AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_AzureStackHCIMachineSpec_To_v1alpha3_AzureStackHCIMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1alpha3_AzureStackHCIMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1alpha3_AzureStackHCIMachineTemplateResource(in *v1alpha4.AzureStackHCIMachineTemplateResource, out *AzureStackHCIMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1alpha3_AzureStackHCIMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(in *AzureStackHCIMachineTemplateSpec, out *v1alpha4.AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_AzureStackHCIMachineTemplateResource_To_v1alpha4_AzureStackHCIMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(in *AzureStackHCIMachineTemplateSpec, out *v1alpha4.AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIMachineTemplateSpec_To_v1alpha4_AzureStackHCIMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1alpha3_AzureStackHCIMachineTemplateSpec(in *v1alpha4.AzureStackHCIMachineTemplateSpec, out *AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_AzureStackHCIMachineTemplateResource_To_v1alpha3_AzureStackHCIMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1alpha3_AzureStackHCIMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1alpha3_AzureStackHCIMachineTemplateSpec(in *v1alpha4.AzureStackHCIMachineTemplateSpec, out *AzureStackHCIMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIMachineTemplateSpec_To_v1alpha3_AzureStackHCIMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference(in *AzureStackHCIResourceReference, out *v1alpha4.AzureStackHCIResourceReference, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	return nil
}

// Convert_v1alpha3_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference(in *AzureStackHCIResourceReference, out *v1alpha4.AzureStackHCIResourceReference, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIResourceReference_To_v1alpha4_AzureStackHCIResourceReference(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIResourceReference_To_v1alpha3_AzureStackHCIResourceReference(in *v1alpha4.AzureStackHCIResourceReference, out *AzureStackHCIResourceReference, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	return nil
}

// Convert_v1alpha4_AzureStackHCIResourceReference_To_v1alpha3_AzureStackHCIResourceReference is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIResourceReference_To_v1alpha3_AzureStackHCIResourceReference(in *v1alpha4.AzureStackHCIResourceReference, out *AzureStackHCIResourceReference, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIResourceReference_To_v1alpha3_AzureStackHCIResourceReference(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine(in *AzureStackHCIVirtualMachine, out *v1alpha4.AzureStackHCIVirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine(in *AzureStackHCIVirtualMachine, out *v1alpha4.AzureStackHCIVirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIVirtualMachine_To_v1alpha4_AzureStackHCIVirtualMachine(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIVirtualMachine_To_v1alpha3_AzureStackHCIVirtualMachine(in *v1alpha4.AzureStackHCIVirtualMachine, out *AzureStackHCIVirtualMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1alpha3_AzureStackHCIVirtualMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1alpha3_AzureStackHCIVirtualMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AzureStackHCIVirtualMachine_To_v1alpha3_AzureStackHCIVirtualMachine is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIVirtualMachine_To_v1alpha3_AzureStackHCIVirtualMachine(in *v1alpha4.AzureStackHCIVirtualMachine, out *AzureStackHCIVirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIVirtualMachine_To_v1alpha3_AzureStackHCIVirtualMachine(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList(in *AzureStackHCIVirtualMachineList, out *v1alpha4.AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.AzureStackHCIVirtualMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList(in *AzureStackHCIVirtualMachineList, out *v1alpha4.AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIVirtualMachineList_To_v1alpha4_AzureStackHCIVirtualMachineList(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1alpha3_AzureStackHCIVirtualMachineList(in *v1alpha4.AzureStackHCIVirtualMachineList, out *AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AzureStackHCIVirtualMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1alpha3_AzureStackHCIVirtualMachineList is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1alpha3_AzureStackHCIVirtualMachineList(in *v1alpha4.AzureStackHCIVirtualMachineList, out *AzureStackHCIVirtualMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIVirtualMachineList_To_v1alpha3_AzureStackHCIVirtualMachineList(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(in *AzureStackHCIVirtualMachineSpec, out *v1alpha4.AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	out.VMSize = in.VMSize
	if err := Convert_v1alpha3_AvailabilityZone_To_v1alpha4_AvailabilityZone(&in.AvailabilityZone, &out.AvailabilityZone, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_OSDisk_To_v1alpha4_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = (*string)(unsafe.Pointer(in.BootstrapData))
	out.Identity = v1alpha4.VMIdentity(in.Identity)
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.ResourceGroup = in.ResourceGroup
	out.VnetName = in.VnetName
	out.ClusterName = in.ClusterName
	out.SubnetName = in.SubnetName
	out.BackendPoolNames = *(*[]string)(unsafe.Pointer(&in.BackendPoolNames))
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	return nil
}

// Convert_v1alpha3_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(in *AzureStackHCIVirtualMachineSpec, out *v1alpha4.AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIVirtualMachineSpec_To_v1alpha4_AzureStackHCIVirtualMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1alpha3_AzureStackHCIVirtualMachineSpec(in *v1alpha4.AzureStackHCIVirtualMachineSpec, out *AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	out.VMSize = in.VMSize
	if err := Convert_v1alpha4_AvailabilityZone_To_v1alpha3_AvailabilityZone(&in.AvailabilityZone, &out.AvailabilityZone, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_Image_To_v1alpha3_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_OSDisk_To_v1alpha3_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = (*string)(unsafe.Pointer(in.BootstrapData))
	out.Identity = VMIdentity(in.Identity)
	out.Location = in.Location
	out.SSHPublicKey = in.SSHPublicKey
	out.ResourceGroup = in.ResourceGroup
	out.VnetName = in.VnetName
	out.ClusterName = in.ClusterName
	out.SubnetName = in.SubnetName
	out.BackendPoolNames = *(*[]string)(unsafe.Pointer(&in.BackendPoolNames))
	out.AdditionalSSHKeys = *(*[]string)(unsafe.Pointer(&in.AdditionalSSHKeys))
	return nil
}

// Convert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1alpha3_AzureStackHCIVirtualMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1alpha3_AzureStackHCIVirtualMachineSpec(in *v1alpha4.AzureStackHCIVirtualMachineSpec, out *AzureStackHCIVirtualMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIVirtualMachineSpec_To_v1alpha3_AzureStackHCIVirtualMachineSpec(in, out, s)
}

func autoConvert_v1alpha3_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(in *AzureStackHCIVirtualMachineStatus, out *v1alpha4.AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*v1alpha4.VMState)(unsafe.Pointer(in.VMState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha3_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus is an autogenerated conversion function.
func Convert_v1alpha3_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(in *AzureStackHCIVirtualMachineStatus, out *v1alpha4.AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_AzureStackHCIVirtualMachineStatus_To_v1alpha4_AzureStackHCIVirtualMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1alpha3_AzureStackHCIVirtualMachineStatus(in *v1alpha4.AzureStackHCIVirtualMachineStatus, out *AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.VMState = (*VMState)(unsafe.Pointer(in.VMState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1alpha3.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1alpha3_AzureStackHCIVirtualMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1alpha3_AzureStackHCIVirtualMachineStatus(in *v1alpha4.AzureStackHCIVirtualMachineStatus, out *AzureStackHCIVirtualMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AzureStackHCIVirtualMachineStatus_To_v1alpha3_AzureStackHCIVirtualMachineStatus(in, out, s)
}

func autoConvert_v1alpha3_Image_To_v1alpha4_Image(in *Image, out *v1alpha4.Image, s conversion.Scope) error {
	out.Publisher = (*string)(unsafe.Pointer(in.Publisher))
	out.Offer = (*string)(unsafe.Pointer(in.Offer))
	out.SKU = (*string)(unsafe.Pointer(in.SKU))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.SubscriptionID = (*string)(unsafe.Pointer(in.SubscriptionID))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.Gallery = (*string)(unsafe.Pointer(in.Gallery))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.OSType = v1alpha4.OSType(in.OSType)
	return nil
}

// Convert_v1alpha3_Image_To_v1alpha4_Image is an autogenerated conversion function.
func Convert_v1alpha3_Image_To_v1alpha4_Image(in *Image, out *v1alpha4.Image, s conversion.Scope) error {
	return autoConvert_v1alpha3_Image_To_v1alpha4_Image(in, out, s)
}

func autoConvert_v1alpha4_Image_To_v1alpha3_Image(in *v1alpha4.Image, out *Image, s conversion.Scope) error {
	out.Publisher = (*string)(unsafe.Pointer(in.Publisher))
	out.Offer = (*string)(unsafe.Pointer(in.Offer))
	out.SKU = (*string)(unsafe.Pointer(in.SKU))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.SubscriptionID = (*string)(unsafe.Pointer(in.SubscriptionID))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.Gallery = (*string)(unsafe.Pointer(in.Gallery))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.OSType = OSType(in.OSType)
	return nil
}

// Convert_v1alpha4_Image_To_v1alpha3_Image is an autogenerated conversion function.
func Convert_v1alpha4_Image_To_v1alpha3_Image(in *v1alpha4.Image, out *Image, s conversion.Scope) error {
	return autoConvert_v1alpha4_Image_To_v1alpha3_Image(in, out, s)
}

func autoConvert_v1alpha3_ManagedDisk_To_v1alpha4_ManagedDisk(in *ManagedDisk, out *v1alpha4.ManagedDisk, s conversion.Scope) error {
	out.StorageAccountType = in.StorageAccountType
	return nil
}

// Convert_v1alpha3_ManagedDisk_To_v1alpha4_ManagedDisk is an autogenerated conversion function.
func Convert_v1alpha3_ManagedDisk_To_v1alpha4_ManagedDisk(in *ManagedDisk, out *v1alpha4.ManagedDisk, s conversion.Scope) error {
	return autoConvert_v1alpha3_ManagedDisk_To_v1alpha4_ManagedDisk(in, out, s)
}

func autoConvert_v1alpha4_ManagedDisk_To_v1alpha3_ManagedDisk(in *v1alpha4.ManagedDisk, out *ManagedDisk, s conversion.Scope) error {
	out.StorageAccountType = in.StorageAccountType
	return nil
}

// Convert_v1alpha4_ManagedDisk_To_v1alpha3_ManagedDisk is an autogenerated conversion function.
func Convert_v1alpha4_ManagedDisk_To_v1alpha3_ManagedDisk(in *v1alpha4.ManagedDisk, out *ManagedDisk, s conversion.Scope) error {
	return autoConvert_v1alpha4_ManagedDisk_To_v1alpha3_ManagedDisk(in, out, s)
}

func autoConvert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec(in *NetworkSpec, out *v1alpha4.NetworkSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_VnetSpec_To_v1alpha4_VnetSpec(&in.Vnet, &out.Vnet, s); err != nil {
		return err
	}
	out.Subnets = *(*v1alpha4.Subnets)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec(in *NetworkSpec, out *v1alpha4.NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_NetworkSpec_To_v1alpha4_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec(in *v1alpha4.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_VnetSpec_To_v1alpha3_VnetSpec(&in.Vnet, &out.Vnet, s); err != nil {
		return err
	}
	out.Subnets = *(*Subnets)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec(in *v1alpha4.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_NetworkSpec_To_v1alpha3_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha3_OSDisk_To_v1alpha4_OSDisk(in *OSDisk, out *v1alpha4.OSDisk, s conversion.Scope) error {
	out.Name = in.Name
	out.Source = in.Source
	out.OSType = v1alpha4.OSType(in.OSType)
	out.DiskSizeGB = in.DiskSizeGB
	if err := Convert_v1alpha3_ManagedDisk_To_v1alpha4_ManagedDisk(&in.ManagedDisk, &out.ManagedDisk, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_OSDisk_To_v1alpha4_OSDisk is an autogenerated conversion function.
func Convert_v1alpha3_OSDisk_To_v1alpha4_OSDisk(in *OSDisk, out *v1alpha4.OSDisk, s conversion.Scope) error {
	return autoConvert_v1alpha3_OSDisk_To_v1alpha4_OSDisk(in, out, s)
}

func autoConvert_v1alpha4_OSDisk_To_v1alpha3_OSDisk(in *v1alpha4.OSDisk, out *OSDisk, s conversion.Scope) error {
	out.Name = in.Name
	out.Source = in.Source
	out.OSType = OSType(in.OSType)
	out.DiskSizeGB = in.DiskSizeGB
	if err := Convert_v1alpha4_ManagedDisk_To_v1alpha3_ManagedDisk(&in.ManagedDisk, &out.ManagedDisk, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OSDisk_To_v1alpha3_OSDisk is an autogenerated conversion function.
func Convert_v1alpha4_OSDisk_To_v1alpha3_OSDisk(in *v1alpha4.OSDisk, out *OSDisk, s conversion.Scope) error {
	return autoConvert_v1alpha4_OSDisk_To_v1alpha3_OSDisk(in, out, s)
}

func autoConvert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec(in *SubnetSpec, out *v1alpha4.SubnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.VnetID = in.VnetID
	out.CidrBlock = in.CidrBlock
	return nil
}

// Convert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec is an autogenerated conversion function.
func Convert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec(in *SubnetSpec, out *v1alpha4.SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_SubnetSpec_To_v1alpha4_SubnetSpec(in, out, s)
}

func autoConvert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec(in *v1alpha4.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.VnetID = in.VnetID
	out.CidrBlock = in.CidrBlock
	return nil
}

// Convert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec is an autogenerated conversion function.
func Convert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec(in *v1alpha4.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_SubnetSpec_To_v1alpha3_SubnetSpec(in, out, s)
}

func autoConvert_v1alpha3_VM_To_v1alpha4_VM(in *VM, out *v1alpha4.VM, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.AvailabilityZone = in.AvailabilityZone
	out.VMSize = in.VMSize
	if err := Convert_v1alpha3_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_OSDisk_To_v1alpha4_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = in.BootstrapData
	out.State = v1alpha4.VMState(in.State)
	out.Identity = v1alpha4.VMIdentity(in.Identity)
	return nil
}

// Convert_v1alpha3_VM_To_v1alpha4_VM is an autogenerated conversion function.
func Convert_v1alpha3_VM_To_v1alpha4_VM(in *VM, out *v1alpha4.VM, s conversion.Scope) error {
	return autoConvert_v1alpha3_VM_To_v1alpha4_VM(in, out, s)
}

func autoConvert_v1alpha4_VM_To_v1alpha3_VM(in *v1alpha4.VM, out *VM, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.AvailabilityZone = in.AvailabilityZone
	out.VMSize = in.VMSize
	if err := Convert_v1alpha4_Image_To_v1alpha3_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_OSDisk_To_v1alpha3_OSDisk(&in.OSDisk, &out.OSDisk, s); err != nil {
		return err
	}
	out.BootstrapData = in.BootstrapData
	out.State = VMState(in.State)
	out.Identity = VMIdentity(in.Identity)
	return nil
}

// Convert_v1alpha4_VM_To_v1alpha3_VM is an autogenerated conversion function.
func Convert_v1alpha4_VM_To_v1alpha3_VM(in *v1alpha4.VM, out *VM, s conversion.Scope) error {
	return autoConvert_v1alpha4_VM_To_v1alpha3_VM(in, out, s)
}

func autoConvert_v1alpha3_VnetSpec_To_v1alpha4_VnetSpec(in *VnetSpec, out *v1alpha4.VnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.CidrBlock = in.CidrBlock
	out.Group = in.Group
	return nil
}

// Convert_v1alpha3_VnetSpec_To_v1alpha4_VnetSpec is an autogenerated conversion function.
func Convert_v1alpha3_VnetSpec_To_v1alpha4_VnetSpec(in *VnetSpec, out *v1alpha4.VnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_VnetSpec_To_v1alpha4_VnetSpec(in, out, s)
}

func autoConvert_v1alpha4_VnetSpec_To_v1alpha3_VnetSpec(in *v1alpha4.VnetSpec, out *VnetSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.CidrBlock = in.CidrBlock
	out.Group = in.Group
	return nil
}

// Convert_v1alpha4_VnetSpec_To_v1alpha3_VnetSpec is an autogenerated conversion function.
func Convert_v1alpha4_VnetSpec_To_v1alpha3_VnetSpec(in *v1alpha4.VnetSpec, out *VnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_VnetSpec_To_v1alpha3_VnetSpec(in, out, s)
}
